syntax = "proto3";

package event.v1;

import "google/protobuf/empty.proto";
import "v1/command/command.proto";

message StationStatus {
  string ip = 1;
  bool logged_in = 2;
}

message StationsState {
  repeated StationStatus status = 1;
}

message SubscribtionEvent {
  oneof message {
    command.v1.CustomCommandOutput command_output = 1;
    StationsState status_update = 2;
  }
}

message ClientCommand {
  repeated string ips = 1;
  oneof command {
    command.v1.LoginWithCredentialsCommand login_with_credentials = 2;
    command.v1.LoginCommand login = 3;
    command.v1.LogoutCommand logout = 4;
    command.v1.CustomCommand custom = 5;
  }
}

service EventsService {
  // Subscribes to the event broadcast
  rpc Subscribe(google.protobuf.Empty) returns (stream SubscribtionEvent) {}
  // Sends a command to the backend that is either send to one or more
  // stations or handled by the backend
  rpc SendCommand(ClientCommand) returns (google.protobuf.Empty) {}
}
