// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ContestsColumns holds the columns for the "contests" table.
	ContestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "start_time", Type: field.TypeTime},
		{Name: "end_time", Type: field.TypeTime},
	}
	// ContestsTable holds the schema information for the "contests" table.
	ContestsTable = &schema.Table{
		Name:       "contests",
		Columns:    ContestsColumns,
		PrimaryKey: []*schema.Column{ContestsColumns[0]},
	}
	// StationsColumns holds the columns for the "stations" table.
	StationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ip", Type: field.TypeString, Unique: true},
		{Name: "connected_at", Type: field.TypeTime},
		{Name: "disconnected_at", Type: field.TypeTime, Nullable: true},
	}
	// StationsTable holds the schema information for the "stations" table.
	StationsTable = &schema.Table{
		Name:       "stations",
		Columns:    StationsColumns,
		PrimaryKey: []*schema.Column{StationsColumns[0]},
	}
	// TeamsColumns holds the columns for the "teams" table.
	TeamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "team_station", Type: field.TypeInt, Nullable: true},
	}
	// TeamsTable holds the schema information for the "teams" table.
	TeamsTable = &schema.Table{
		Name:       "teams",
		Columns:    TeamsColumns,
		PrimaryKey: []*schema.Column{TeamsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "teams_stations_station",
				Columns:    []*schema.Column{TeamsColumns[2]},
				RefColumns: []*schema.Column{StationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// WallpapersColumns holds the columns for the "wallpapers" table.
	WallpapersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "image_data", Type: field.TypeBytes, Nullable: true},
		{Name: "contest_id", Type: field.TypeString},
	}
	// WallpapersTable holds the schema information for the "wallpapers" table.
	WallpapersTable = &schema.Table{
		Name:       "wallpapers",
		Columns:    WallpapersColumns,
		PrimaryKey: []*schema.Column{WallpapersColumns[0]},
	}
	// ContestTeamsColumns holds the columns for the "contest_teams" table.
	ContestTeamsColumns = []*schema.Column{
		{Name: "contest_id", Type: field.TypeString},
		{Name: "team_id", Type: field.TypeString},
	}
	// ContestTeamsTable holds the schema information for the "contest_teams" table.
	ContestTeamsTable = &schema.Table{
		Name:       "contest_teams",
		Columns:    ContestTeamsColumns,
		PrimaryKey: []*schema.Column{ContestTeamsColumns[0], ContestTeamsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "contest_teams_contest_id",
				Columns:    []*schema.Column{ContestTeamsColumns[0]},
				RefColumns: []*schema.Column{ContestsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "contest_teams_team_id",
				Columns:    []*schema.Column{ContestTeamsColumns[1]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ContestsTable,
		StationsTable,
		TeamsTable,
		WallpapersTable,
		ContestTeamsTable,
	}
)

func init() {
	TeamsTable.ForeignKeys[0].RefTable = StationsTable
	ContestTeamsTable.ForeignKeys[0].RefTable = ContestsTable
	ContestTeamsTable.ForeignKeys[1].RefTable = TeamsTable
}
