// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ContestsColumns holds the columns for the "contests" table.
	ContestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "start_time", Type: field.TypeTime},
		{Name: "end_time", Type: field.TypeTime},
	}
	// ContestsTable holds the schema information for the "contests" table.
	ContestsTable = &schema.Table{
		Name:       "contests",
		Columns:    ContestsColumns,
		PrimaryKey: []*schema.Column{ContestsColumns[0]},
	}
	// ContestAreaMapsColumns holds the columns for the "contest_area_maps" table.
	ContestAreaMapsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// ContestAreaMapsTable holds the schema information for the "contest_area_maps" table.
	ContestAreaMapsTable = &schema.Table{
		Name:       "contest_area_maps",
		Columns:    ContestAreaMapsColumns,
		PrimaryKey: []*schema.Column{ContestAreaMapsColumns[0]},
	}
	// ContestMapsColumns holds the columns for the "contest_maps" table.
	ContestMapsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "contest_id", Type: field.TypeString, Unique: true},
		{Name: "map_id", Type: field.TypeInt},
	}
	// ContestMapsTable holds the schema information for the "contest_maps" table.
	ContestMapsTable = &schema.Table{
		Name:       "contest_maps",
		Columns:    ContestMapsColumns,
		PrimaryKey: []*schema.Column{ContestMapsColumns[0]},
	}
	// DoorElementsColumns holds the columns for the "door_elements" table.
	DoorElementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "x", Type: field.TypeInt},
		{Name: "y", Type: field.TypeInt},
		{Name: "rotation", Type: field.TypeEnum, Enums: []string{"0", "90", "180", "270"}, Default: "0"},
		{Name: "contest_area_map_doors", Type: field.TypeInt, Nullable: true},
	}
	// DoorElementsTable holds the schema information for the "door_elements" table.
	DoorElementsTable = &schema.Table{
		Name:       "door_elements",
		Columns:    DoorElementsColumns,
		PrimaryKey: []*schema.Column{DoorElementsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "door_elements_contest_area_maps_doors",
				Columns:    []*schema.Column{DoorElementsColumns[4]},
				RefColumns: []*schema.Column{ContestAreaMapsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// StationsColumns holds the columns for the "stations" table.
	StationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ip", Type: field.TypeString, Unique: true},
		{Name: "connected_at", Type: field.TypeTime},
		{Name: "disconnected_at", Type: field.TypeTime, Nullable: true},
	}
	// StationsTable holds the schema information for the "stations" table.
	StationsTable = &schema.Table{
		Name:       "stations",
		Columns:    StationsColumns,
		PrimaryKey: []*schema.Column{StationsColumns[0]},
	}
	// TableElementsColumns holds the columns for the "table_elements" table.
	TableElementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "x", Type: field.TypeInt},
		{Name: "y", Type: field.TypeInt},
		{Name: "rotation", Type: field.TypeEnum, Enums: []string{"0", "90", "180", "270"}, Default: "0"},
		{Name: "contest_area_map_tables", Type: field.TypeInt, Nullable: true},
		{Name: "table_element_station", Type: field.TypeInt, Nullable: true},
	}
	// TableElementsTable holds the schema information for the "table_elements" table.
	TableElementsTable = &schema.Table{
		Name:       "table_elements",
		Columns:    TableElementsColumns,
		PrimaryKey: []*schema.Column{TableElementsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "table_elements_contest_area_maps_tables",
				Columns:    []*schema.Column{TableElementsColumns[4]},
				RefColumns: []*schema.Column{ContestAreaMapsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "table_elements_stations_station",
				Columns:    []*schema.Column{TableElementsColumns[5]},
				RefColumns: []*schema.Column{StationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TeamsColumns holds the columns for the "teams" table.
	TeamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "team_station", Type: field.TypeInt, Nullable: true},
	}
	// TeamsTable holds the schema information for the "teams" table.
	TeamsTable = &schema.Table{
		Name:       "teams",
		Columns:    TeamsColumns,
		PrimaryKey: []*schema.Column{TeamsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "teams_stations_station",
				Columns:    []*schema.Column{TeamsColumns[2]},
				RefColumns: []*schema.Column{StationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// WallElementsColumns holds the columns for the "wall_elements" table.
	WallElementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "x_start", Type: field.TypeInt},
		{Name: "y_start", Type: field.TypeInt},
		{Name: "x_end", Type: field.TypeInt},
		{Name: "y_end", Type: field.TypeInt},
		{Name: "contest_area_map_walls", Type: field.TypeInt, Nullable: true},
	}
	// WallElementsTable holds the schema information for the "wall_elements" table.
	WallElementsTable = &schema.Table{
		Name:       "wall_elements",
		Columns:    WallElementsColumns,
		PrimaryKey: []*schema.Column{WallElementsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "wall_elements_contest_area_maps_walls",
				Columns:    []*schema.Column{WallElementsColumns[5]},
				RefColumns: []*schema.Column{ContestAreaMapsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// WallpapersColumns holds the columns for the "wallpapers" table.
	WallpapersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "image_data", Type: field.TypeBytes},
		{Name: "contest_id", Type: field.TypeString, Unique: true},
	}
	// WallpapersTable holds the schema information for the "wallpapers" table.
	WallpapersTable = &schema.Table{
		Name:       "wallpapers",
		Columns:    WallpapersColumns,
		PrimaryKey: []*schema.Column{WallpapersColumns[0]},
	}
	// ContestTeamsColumns holds the columns for the "contest_teams" table.
	ContestTeamsColumns = []*schema.Column{
		{Name: "contest_id", Type: field.TypeString},
		{Name: "team_id", Type: field.TypeString},
	}
	// ContestTeamsTable holds the schema information for the "contest_teams" table.
	ContestTeamsTable = &schema.Table{
		Name:       "contest_teams",
		Columns:    ContestTeamsColumns,
		PrimaryKey: []*schema.Column{ContestTeamsColumns[0], ContestTeamsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "contest_teams_contest_id",
				Columns:    []*schema.Column{ContestTeamsColumns[0]},
				RefColumns: []*schema.Column{ContestsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "contest_teams_team_id",
				Columns:    []*schema.Column{ContestTeamsColumns[1]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ContestsTable,
		ContestAreaMapsTable,
		ContestMapsTable,
		DoorElementsTable,
		StationsTable,
		TableElementsTable,
		TeamsTable,
		WallElementsTable,
		WallpapersTable,
		ContestTeamsTable,
	}
)

func init() {
	DoorElementsTable.ForeignKeys[0].RefTable = ContestAreaMapsTable
	TableElementsTable.ForeignKeys[0].RefTable = ContestAreaMapsTable
	TableElementsTable.ForeignKeys[1].RefTable = StationsTable
	TeamsTable.ForeignKeys[0].RefTable = StationsTable
	WallElementsTable.ForeignKeys[0].RefTable = ContestAreaMapsTable
	ContestTeamsTable.ForeignKeys[0].RefTable = ContestsTable
	ContestTeamsTable.ForeignKeys[1].RefTable = TeamsTable
}
