[package]
name = "loom-client"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.20.0", features = ["v7", "js"] }
loom-map-types = { path = "../map/types", optional = true }
futures = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
loom-rpc = { path = "../../gen/rs" }
tonic = { version = "0.14", default-features = false, features = [ "transport"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
loom-rpc = { path = "../../gen/rs", default-features = false, features = ["wasm"] }
tonic-web-wasm-client = "0.8"

[features]
map = ["loom-rpc/map-v1", "dep:loom-map-types"]
broadcast = ["loom-rpc/broadcast-v1"]
all = ["map", "broadcast"]
