// Code generated by ent, DO NOT EDIT.

package doorelement

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the doorelement type in the database.
	Label = "door_element"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldX holds the string denoting the x field in the database.
	FieldX = "x"
	// FieldY holds the string denoting the y field in the database.
	FieldY = "y"
	// FieldRotation holds the string denoting the rotation field in the database.
	FieldRotation = "rotation"
	// EdgeMap holds the string denoting the map edge name in mutations.
	EdgeMap = "map"
	// Table holds the table name of the doorelement in the database.
	Table = "door_elements"
	// MapTable is the table that holds the map relation/edge.
	MapTable = "door_elements"
	// MapInverseTable is the table name for the ContestAreaMap entity.
	// It exists in this package in order to avoid circular dependency with the "contestareamap" package.
	MapInverseTable = "contest_area_maps"
	// MapColumn is the table column denoting the map relation/edge.
	MapColumn = "contest_area_map_doors"
)

// Columns holds all SQL columns for doorelement fields.
var Columns = []string{
	FieldID,
	FieldX,
	FieldY,
	FieldRotation,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "door_elements"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"contest_area_map_doors",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Rotation defines the type for the "rotation" enum field.
type Rotation string

// Rotation0 is the default value of the Rotation enum.
const DefaultRotation = Rotation0

// Rotation values.
const (
	Rotation0   Rotation = "0"
	Rotation90  Rotation = "90"
	Rotation180 Rotation = "180"
	Rotation270 Rotation = "270"
)

func (r Rotation) String() string {
	return string(r)
}

// RotationValidator is a validator for the "rotation" field enum values. It is called by the builders before save.
func RotationValidator(r Rotation) error {
	switch r {
	case Rotation0, Rotation90, Rotation180, Rotation270:
		return nil
	default:
		return fmt.Errorf("doorelement: invalid enum value for rotation field: %q", r)
	}
}

// OrderOption defines the ordering options for the DoorElement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByX orders the results by the x field.
func ByX(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldX, opts...).ToFunc()
}

// ByY orders the results by the y field.
func ByY(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldY, opts...).ToFunc()
}

// ByRotation orders the results by the rotation field.
func ByRotation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRotation, opts...).ToFunc()
}

// ByMapField orders the results by map field.
func ByMapField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMapStep(), sql.OrderByField(field, opts...))
	}
}
func newMapStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MapInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MapTable, MapColumn),
	)
}
