// Code generated by ent, DO NOT EDIT.

package doorelement

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldLTE(FieldID, id))
}

// X applies equality check predicate on the "x" field. It's identical to XEQ.
func X(v int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldEQ(FieldX, v))
}

// Y applies equality check predicate on the "y" field. It's identical to YEQ.
func Y(v int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldEQ(FieldY, v))
}

// XEQ applies the EQ predicate on the "x" field.
func XEQ(v int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldEQ(FieldX, v))
}

// XNEQ applies the NEQ predicate on the "x" field.
func XNEQ(v int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldNEQ(FieldX, v))
}

// XIn applies the In predicate on the "x" field.
func XIn(vs ...int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldIn(FieldX, vs...))
}

// XNotIn applies the NotIn predicate on the "x" field.
func XNotIn(vs ...int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldNotIn(FieldX, vs...))
}

// XGT applies the GT predicate on the "x" field.
func XGT(v int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldGT(FieldX, v))
}

// XGTE applies the GTE predicate on the "x" field.
func XGTE(v int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldGTE(FieldX, v))
}

// XLT applies the LT predicate on the "x" field.
func XLT(v int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldLT(FieldX, v))
}

// XLTE applies the LTE predicate on the "x" field.
func XLTE(v int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldLTE(FieldX, v))
}

// YEQ applies the EQ predicate on the "y" field.
func YEQ(v int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldEQ(FieldY, v))
}

// YNEQ applies the NEQ predicate on the "y" field.
func YNEQ(v int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldNEQ(FieldY, v))
}

// YIn applies the In predicate on the "y" field.
func YIn(vs ...int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldIn(FieldY, vs...))
}

// YNotIn applies the NotIn predicate on the "y" field.
func YNotIn(vs ...int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldNotIn(FieldY, vs...))
}

// YGT applies the GT predicate on the "y" field.
func YGT(v int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldGT(FieldY, v))
}

// YGTE applies the GTE predicate on the "y" field.
func YGTE(v int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldGTE(FieldY, v))
}

// YLT applies the LT predicate on the "y" field.
func YLT(v int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldLT(FieldY, v))
}

// YLTE applies the LTE predicate on the "y" field.
func YLTE(v int) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldLTE(FieldY, v))
}

// RotationEQ applies the EQ predicate on the "rotation" field.
func RotationEQ(v Rotation) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldEQ(FieldRotation, v))
}

// RotationNEQ applies the NEQ predicate on the "rotation" field.
func RotationNEQ(v Rotation) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldNEQ(FieldRotation, v))
}

// RotationIn applies the In predicate on the "rotation" field.
func RotationIn(vs ...Rotation) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldIn(FieldRotation, vs...))
}

// RotationNotIn applies the NotIn predicate on the "rotation" field.
func RotationNotIn(vs ...Rotation) predicate.DoorElement {
	return predicate.DoorElement(sql.FieldNotIn(FieldRotation, vs...))
}

// HasMap applies the HasEdge predicate on the "map" edge.
func HasMap() predicate.DoorElement {
	return predicate.DoorElement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MapTable, MapColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMapWith applies the HasEdge predicate on the "map" edge with a given conditions (other predicates).
func HasMapWith(preds ...predicate.ContestAreaMap) predicate.DoorElement {
	return predicate.DoorElement(func(s *sql.Selector) {
		step := newMapStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DoorElement) predicate.DoorElement {
	return predicate.DoorElement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DoorElement) predicate.DoorElement {
	return predicate.DoorElement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DoorElement) predicate.DoorElement {
	return predicate.DoorElement(sql.NotPredicates(p))
}
