// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/migrate"
	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/contest"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/contestareamap"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/contestmap"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/doorelement"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/station"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/tableelement"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/team"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/wallelement"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/wallpaper"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Contest is the client for interacting with the Contest builders.
	Contest *ContestClient
	// ContestAreaMap is the client for interacting with the ContestAreaMap builders.
	ContestAreaMap *ContestAreaMapClient
	// ContestMap is the client for interacting with the ContestMap builders.
	ContestMap *ContestMapClient
	// DoorElement is the client for interacting with the DoorElement builders.
	DoorElement *DoorElementClient
	// Station is the client for interacting with the Station builders.
	Station *StationClient
	// TableElement is the client for interacting with the TableElement builders.
	TableElement *TableElementClient
	// Team is the client for interacting with the Team builders.
	Team *TeamClient
	// WallElement is the client for interacting with the WallElement builders.
	WallElement *WallElementClient
	// Wallpaper is the client for interacting with the Wallpaper builders.
	Wallpaper *WallpaperClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Contest = NewContestClient(c.config)
	c.ContestAreaMap = NewContestAreaMapClient(c.config)
	c.ContestMap = NewContestMapClient(c.config)
	c.DoorElement = NewDoorElementClient(c.config)
	c.Station = NewStationClient(c.config)
	c.TableElement = NewTableElementClient(c.config)
	c.Team = NewTeamClient(c.config)
	c.WallElement = NewWallElementClient(c.config)
	c.Wallpaper = NewWallpaperClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Contest:        NewContestClient(cfg),
		ContestAreaMap: NewContestAreaMapClient(cfg),
		ContestMap:     NewContestMapClient(cfg),
		DoorElement:    NewDoorElementClient(cfg),
		Station:        NewStationClient(cfg),
		TableElement:   NewTableElementClient(cfg),
		Team:           NewTeamClient(cfg),
		WallElement:    NewWallElementClient(cfg),
		Wallpaper:      NewWallpaperClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Contest:        NewContestClient(cfg),
		ContestAreaMap: NewContestAreaMapClient(cfg),
		ContestMap:     NewContestMapClient(cfg),
		DoorElement:    NewDoorElementClient(cfg),
		Station:        NewStationClient(cfg),
		TableElement:   NewTableElementClient(cfg),
		Team:           NewTeamClient(cfg),
		WallElement:    NewWallElementClient(cfg),
		Wallpaper:      NewWallpaperClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Contest.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Contest, c.ContestAreaMap, c.ContestMap, c.DoorElement, c.Station,
		c.TableElement, c.Team, c.WallElement, c.Wallpaper,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Contest, c.ContestAreaMap, c.ContestMap, c.DoorElement, c.Station,
		c.TableElement, c.Team, c.WallElement, c.Wallpaper,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ContestMutation:
		return c.Contest.mutate(ctx, m)
	case *ContestAreaMapMutation:
		return c.ContestAreaMap.mutate(ctx, m)
	case *ContestMapMutation:
		return c.ContestMap.mutate(ctx, m)
	case *DoorElementMutation:
		return c.DoorElement.mutate(ctx, m)
	case *StationMutation:
		return c.Station.mutate(ctx, m)
	case *TableElementMutation:
		return c.TableElement.mutate(ctx, m)
	case *TeamMutation:
		return c.Team.mutate(ctx, m)
	case *WallElementMutation:
		return c.WallElement.mutate(ctx, m)
	case *WallpaperMutation:
		return c.Wallpaper.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ContestClient is a client for the Contest schema.
type ContestClient struct {
	config
}

// NewContestClient returns a client for the Contest from the given config.
func NewContestClient(c config) *ContestClient {
	return &ContestClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `contest.Hooks(f(g(h())))`.
func (c *ContestClient) Use(hooks ...Hook) {
	c.hooks.Contest = append(c.hooks.Contest, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `contest.Intercept(f(g(h())))`.
func (c *ContestClient) Intercept(interceptors ...Interceptor) {
	c.inters.Contest = append(c.inters.Contest, interceptors...)
}

// Create returns a builder for creating a Contest entity.
func (c *ContestClient) Create() *ContestCreate {
	mutation := newContestMutation(c.config, OpCreate)
	return &ContestCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Contest entities.
func (c *ContestClient) CreateBulk(builders ...*ContestCreate) *ContestCreateBulk {
	return &ContestCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ContestClient) MapCreateBulk(slice any, setFunc func(*ContestCreate, int)) *ContestCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ContestCreateBulk{err: fmt.Errorf("calling to ContestClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ContestCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ContestCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Contest.
func (c *ContestClient) Update() *ContestUpdate {
	mutation := newContestMutation(c.config, OpUpdate)
	return &ContestUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ContestClient) UpdateOne(_m *Contest) *ContestUpdateOne {
	mutation := newContestMutation(c.config, OpUpdateOne, withContest(_m))
	return &ContestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ContestClient) UpdateOneID(id string) *ContestUpdateOne {
	mutation := newContestMutation(c.config, OpUpdateOne, withContestID(id))
	return &ContestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Contest.
func (c *ContestClient) Delete() *ContestDelete {
	mutation := newContestMutation(c.config, OpDelete)
	return &ContestDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ContestClient) DeleteOne(_m *Contest) *ContestDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ContestClient) DeleteOneID(id string) *ContestDeleteOne {
	builder := c.Delete().Where(contest.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ContestDeleteOne{builder}
}

// Query returns a query builder for Contest.
func (c *ContestClient) Query() *ContestQuery {
	return &ContestQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeContest},
		inters: c.Interceptors(),
	}
}

// Get returns a Contest entity by its id.
func (c *ContestClient) Get(ctx context.Context, id string) (*Contest, error) {
	return c.Query().Where(contest.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ContestClient) GetX(ctx context.Context, id string) *Contest {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTeams queries the teams edge of a Contest.
func (c *ContestClient) QueryTeams(_m *Contest) *TeamQuery {
	query := (&TeamClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(contest.Table, contest.FieldID, id),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, contest.TeamsTable, contest.TeamsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ContestClient) Hooks() []Hook {
	return c.hooks.Contest
}

// Interceptors returns the client interceptors.
func (c *ContestClient) Interceptors() []Interceptor {
	return c.inters.Contest
}

func (c *ContestClient) mutate(ctx context.Context, m *ContestMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ContestCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ContestUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ContestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ContestDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Contest mutation op: %q", m.Op())
	}
}

// ContestAreaMapClient is a client for the ContestAreaMap schema.
type ContestAreaMapClient struct {
	config
}

// NewContestAreaMapClient returns a client for the ContestAreaMap from the given config.
func NewContestAreaMapClient(c config) *ContestAreaMapClient {
	return &ContestAreaMapClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `contestareamap.Hooks(f(g(h())))`.
func (c *ContestAreaMapClient) Use(hooks ...Hook) {
	c.hooks.ContestAreaMap = append(c.hooks.ContestAreaMap, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `contestareamap.Intercept(f(g(h())))`.
func (c *ContestAreaMapClient) Intercept(interceptors ...Interceptor) {
	c.inters.ContestAreaMap = append(c.inters.ContestAreaMap, interceptors...)
}

// Create returns a builder for creating a ContestAreaMap entity.
func (c *ContestAreaMapClient) Create() *ContestAreaMapCreate {
	mutation := newContestAreaMapMutation(c.config, OpCreate)
	return &ContestAreaMapCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ContestAreaMap entities.
func (c *ContestAreaMapClient) CreateBulk(builders ...*ContestAreaMapCreate) *ContestAreaMapCreateBulk {
	return &ContestAreaMapCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ContestAreaMapClient) MapCreateBulk(slice any, setFunc func(*ContestAreaMapCreate, int)) *ContestAreaMapCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ContestAreaMapCreateBulk{err: fmt.Errorf("calling to ContestAreaMapClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ContestAreaMapCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ContestAreaMapCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ContestAreaMap.
func (c *ContestAreaMapClient) Update() *ContestAreaMapUpdate {
	mutation := newContestAreaMapMutation(c.config, OpUpdate)
	return &ContestAreaMapUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ContestAreaMapClient) UpdateOne(_m *ContestAreaMap) *ContestAreaMapUpdateOne {
	mutation := newContestAreaMapMutation(c.config, OpUpdateOne, withContestAreaMap(_m))
	return &ContestAreaMapUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ContestAreaMapClient) UpdateOneID(id int) *ContestAreaMapUpdateOne {
	mutation := newContestAreaMapMutation(c.config, OpUpdateOne, withContestAreaMapID(id))
	return &ContestAreaMapUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ContestAreaMap.
func (c *ContestAreaMapClient) Delete() *ContestAreaMapDelete {
	mutation := newContestAreaMapMutation(c.config, OpDelete)
	return &ContestAreaMapDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ContestAreaMapClient) DeleteOne(_m *ContestAreaMap) *ContestAreaMapDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ContestAreaMapClient) DeleteOneID(id int) *ContestAreaMapDeleteOne {
	builder := c.Delete().Where(contestareamap.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ContestAreaMapDeleteOne{builder}
}

// Query returns a query builder for ContestAreaMap.
func (c *ContestAreaMapClient) Query() *ContestAreaMapQuery {
	return &ContestAreaMapQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeContestAreaMap},
		inters: c.Interceptors(),
	}
}

// Get returns a ContestAreaMap entity by its id.
func (c *ContestAreaMapClient) Get(ctx context.Context, id int) (*ContestAreaMap, error) {
	return c.Query().Where(contestareamap.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ContestAreaMapClient) GetX(ctx context.Context, id int) *ContestAreaMap {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDoors queries the doors edge of a ContestAreaMap.
func (c *ContestAreaMapClient) QueryDoors(_m *ContestAreaMap) *DoorElementQuery {
	query := (&DoorElementClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(contestareamap.Table, contestareamap.FieldID, id),
			sqlgraph.To(doorelement.Table, doorelement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contestareamap.DoorsTable, contestareamap.DoorsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryWalls queries the walls edge of a ContestAreaMap.
func (c *ContestAreaMapClient) QueryWalls(_m *ContestAreaMap) *WallElementQuery {
	query := (&WallElementClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(contestareamap.Table, contestareamap.FieldID, id),
			sqlgraph.To(wallelement.Table, wallelement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contestareamap.WallsTable, contestareamap.WallsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTables queries the tables edge of a ContestAreaMap.
func (c *ContestAreaMapClient) QueryTables(_m *ContestAreaMap) *TableElementQuery {
	query := (&TableElementClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(contestareamap.Table, contestareamap.FieldID, id),
			sqlgraph.To(tableelement.Table, tableelement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contestareamap.TablesTable, contestareamap.TablesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ContestAreaMapClient) Hooks() []Hook {
	return c.hooks.ContestAreaMap
}

// Interceptors returns the client interceptors.
func (c *ContestAreaMapClient) Interceptors() []Interceptor {
	return c.inters.ContestAreaMap
}

func (c *ContestAreaMapClient) mutate(ctx context.Context, m *ContestAreaMapMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ContestAreaMapCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ContestAreaMapUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ContestAreaMapUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ContestAreaMapDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ContestAreaMap mutation op: %q", m.Op())
	}
}

// ContestMapClient is a client for the ContestMap schema.
type ContestMapClient struct {
	config
}

// NewContestMapClient returns a client for the ContestMap from the given config.
func NewContestMapClient(c config) *ContestMapClient {
	return &ContestMapClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `contestmap.Hooks(f(g(h())))`.
func (c *ContestMapClient) Use(hooks ...Hook) {
	c.hooks.ContestMap = append(c.hooks.ContestMap, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `contestmap.Intercept(f(g(h())))`.
func (c *ContestMapClient) Intercept(interceptors ...Interceptor) {
	c.inters.ContestMap = append(c.inters.ContestMap, interceptors...)
}

// Create returns a builder for creating a ContestMap entity.
func (c *ContestMapClient) Create() *ContestMapCreate {
	mutation := newContestMapMutation(c.config, OpCreate)
	return &ContestMapCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ContestMap entities.
func (c *ContestMapClient) CreateBulk(builders ...*ContestMapCreate) *ContestMapCreateBulk {
	return &ContestMapCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ContestMapClient) MapCreateBulk(slice any, setFunc func(*ContestMapCreate, int)) *ContestMapCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ContestMapCreateBulk{err: fmt.Errorf("calling to ContestMapClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ContestMapCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ContestMapCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ContestMap.
func (c *ContestMapClient) Update() *ContestMapUpdate {
	mutation := newContestMapMutation(c.config, OpUpdate)
	return &ContestMapUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ContestMapClient) UpdateOne(_m *ContestMap) *ContestMapUpdateOne {
	mutation := newContestMapMutation(c.config, OpUpdateOne, withContestMap(_m))
	return &ContestMapUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ContestMapClient) UpdateOneID(id int) *ContestMapUpdateOne {
	mutation := newContestMapMutation(c.config, OpUpdateOne, withContestMapID(id))
	return &ContestMapUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ContestMap.
func (c *ContestMapClient) Delete() *ContestMapDelete {
	mutation := newContestMapMutation(c.config, OpDelete)
	return &ContestMapDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ContestMapClient) DeleteOne(_m *ContestMap) *ContestMapDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ContestMapClient) DeleteOneID(id int) *ContestMapDeleteOne {
	builder := c.Delete().Where(contestmap.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ContestMapDeleteOne{builder}
}

// Query returns a query builder for ContestMap.
func (c *ContestMapClient) Query() *ContestMapQuery {
	return &ContestMapQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeContestMap},
		inters: c.Interceptors(),
	}
}

// Get returns a ContestMap entity by its id.
func (c *ContestMapClient) Get(ctx context.Context, id int) (*ContestMap, error) {
	return c.Query().Where(contestmap.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ContestMapClient) GetX(ctx context.Context, id int) *ContestMap {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ContestMapClient) Hooks() []Hook {
	return c.hooks.ContestMap
}

// Interceptors returns the client interceptors.
func (c *ContestMapClient) Interceptors() []Interceptor {
	return c.inters.ContestMap
}

func (c *ContestMapClient) mutate(ctx context.Context, m *ContestMapMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ContestMapCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ContestMapUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ContestMapUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ContestMapDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ContestMap mutation op: %q", m.Op())
	}
}

// DoorElementClient is a client for the DoorElement schema.
type DoorElementClient struct {
	config
}

// NewDoorElementClient returns a client for the DoorElement from the given config.
func NewDoorElementClient(c config) *DoorElementClient {
	return &DoorElementClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `doorelement.Hooks(f(g(h())))`.
func (c *DoorElementClient) Use(hooks ...Hook) {
	c.hooks.DoorElement = append(c.hooks.DoorElement, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `doorelement.Intercept(f(g(h())))`.
func (c *DoorElementClient) Intercept(interceptors ...Interceptor) {
	c.inters.DoorElement = append(c.inters.DoorElement, interceptors...)
}

// Create returns a builder for creating a DoorElement entity.
func (c *DoorElementClient) Create() *DoorElementCreate {
	mutation := newDoorElementMutation(c.config, OpCreate)
	return &DoorElementCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DoorElement entities.
func (c *DoorElementClient) CreateBulk(builders ...*DoorElementCreate) *DoorElementCreateBulk {
	return &DoorElementCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DoorElementClient) MapCreateBulk(slice any, setFunc func(*DoorElementCreate, int)) *DoorElementCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DoorElementCreateBulk{err: fmt.Errorf("calling to DoorElementClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DoorElementCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DoorElementCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DoorElement.
func (c *DoorElementClient) Update() *DoorElementUpdate {
	mutation := newDoorElementMutation(c.config, OpUpdate)
	return &DoorElementUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DoorElementClient) UpdateOne(_m *DoorElement) *DoorElementUpdateOne {
	mutation := newDoorElementMutation(c.config, OpUpdateOne, withDoorElement(_m))
	return &DoorElementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DoorElementClient) UpdateOneID(id uuid.UUID) *DoorElementUpdateOne {
	mutation := newDoorElementMutation(c.config, OpUpdateOne, withDoorElementID(id))
	return &DoorElementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DoorElement.
func (c *DoorElementClient) Delete() *DoorElementDelete {
	mutation := newDoorElementMutation(c.config, OpDelete)
	return &DoorElementDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DoorElementClient) DeleteOne(_m *DoorElement) *DoorElementDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DoorElementClient) DeleteOneID(id uuid.UUID) *DoorElementDeleteOne {
	builder := c.Delete().Where(doorelement.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DoorElementDeleteOne{builder}
}

// Query returns a query builder for DoorElement.
func (c *DoorElementClient) Query() *DoorElementQuery {
	return &DoorElementQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDoorElement},
		inters: c.Interceptors(),
	}
}

// Get returns a DoorElement entity by its id.
func (c *DoorElementClient) Get(ctx context.Context, id uuid.UUID) (*DoorElement, error) {
	return c.Query().Where(doorelement.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DoorElementClient) GetX(ctx context.Context, id uuid.UUID) *DoorElement {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMap queries the map edge of a DoorElement.
func (c *DoorElementClient) QueryMap(_m *DoorElement) *ContestAreaMapQuery {
	query := (&ContestAreaMapClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(doorelement.Table, doorelement.FieldID, id),
			sqlgraph.To(contestareamap.Table, contestareamap.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, doorelement.MapTable, doorelement.MapColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DoorElementClient) Hooks() []Hook {
	return c.hooks.DoorElement
}

// Interceptors returns the client interceptors.
func (c *DoorElementClient) Interceptors() []Interceptor {
	return c.inters.DoorElement
}

func (c *DoorElementClient) mutate(ctx context.Context, m *DoorElementMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DoorElementCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DoorElementUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DoorElementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DoorElementDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DoorElement mutation op: %q", m.Op())
	}
}

// StationClient is a client for the Station schema.
type StationClient struct {
	config
}

// NewStationClient returns a client for the Station from the given config.
func NewStationClient(c config) *StationClient {
	return &StationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `station.Hooks(f(g(h())))`.
func (c *StationClient) Use(hooks ...Hook) {
	c.hooks.Station = append(c.hooks.Station, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `station.Intercept(f(g(h())))`.
func (c *StationClient) Intercept(interceptors ...Interceptor) {
	c.inters.Station = append(c.inters.Station, interceptors...)
}

// Create returns a builder for creating a Station entity.
func (c *StationClient) Create() *StationCreate {
	mutation := newStationMutation(c.config, OpCreate)
	return &StationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Station entities.
func (c *StationClient) CreateBulk(builders ...*StationCreate) *StationCreateBulk {
	return &StationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StationClient) MapCreateBulk(slice any, setFunc func(*StationCreate, int)) *StationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StationCreateBulk{err: fmt.Errorf("calling to StationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Station.
func (c *StationClient) Update() *StationUpdate {
	mutation := newStationMutation(c.config, OpUpdate)
	return &StationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StationClient) UpdateOne(_m *Station) *StationUpdateOne {
	mutation := newStationMutation(c.config, OpUpdateOne, withStation(_m))
	return &StationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StationClient) UpdateOneID(id int) *StationUpdateOne {
	mutation := newStationMutation(c.config, OpUpdateOne, withStationID(id))
	return &StationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Station.
func (c *StationClient) Delete() *StationDelete {
	mutation := newStationMutation(c.config, OpDelete)
	return &StationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StationClient) DeleteOne(_m *Station) *StationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StationClient) DeleteOneID(id int) *StationDeleteOne {
	builder := c.Delete().Where(station.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StationDeleteOne{builder}
}

// Query returns a query builder for Station.
func (c *StationClient) Query() *StationQuery {
	return &StationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStation},
		inters: c.Interceptors(),
	}
}

// Get returns a Station entity by its id.
func (c *StationClient) Get(ctx context.Context, id int) (*Station, error) {
	return c.Query().Where(station.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StationClient) GetX(ctx context.Context, id int) *Station {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTableElement queries the table_element edge of a Station.
func (c *StationClient) QueryTableElement(_m *Station) *TableElementQuery {
	query := (&TableElementClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(station.Table, station.FieldID, id),
			sqlgraph.To(tableelement.Table, tableelement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, station.TableElementTable, station.TableElementColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StationClient) Hooks() []Hook {
	return c.hooks.Station
}

// Interceptors returns the client interceptors.
func (c *StationClient) Interceptors() []Interceptor {
	return c.inters.Station
}

func (c *StationClient) mutate(ctx context.Context, m *StationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Station mutation op: %q", m.Op())
	}
}

// TableElementClient is a client for the TableElement schema.
type TableElementClient struct {
	config
}

// NewTableElementClient returns a client for the TableElement from the given config.
func NewTableElementClient(c config) *TableElementClient {
	return &TableElementClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tableelement.Hooks(f(g(h())))`.
func (c *TableElementClient) Use(hooks ...Hook) {
	c.hooks.TableElement = append(c.hooks.TableElement, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tableelement.Intercept(f(g(h())))`.
func (c *TableElementClient) Intercept(interceptors ...Interceptor) {
	c.inters.TableElement = append(c.inters.TableElement, interceptors...)
}

// Create returns a builder for creating a TableElement entity.
func (c *TableElementClient) Create() *TableElementCreate {
	mutation := newTableElementMutation(c.config, OpCreate)
	return &TableElementCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TableElement entities.
func (c *TableElementClient) CreateBulk(builders ...*TableElementCreate) *TableElementCreateBulk {
	return &TableElementCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TableElementClient) MapCreateBulk(slice any, setFunc func(*TableElementCreate, int)) *TableElementCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TableElementCreateBulk{err: fmt.Errorf("calling to TableElementClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TableElementCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TableElementCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TableElement.
func (c *TableElementClient) Update() *TableElementUpdate {
	mutation := newTableElementMutation(c.config, OpUpdate)
	return &TableElementUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TableElementClient) UpdateOne(_m *TableElement) *TableElementUpdateOne {
	mutation := newTableElementMutation(c.config, OpUpdateOne, withTableElement(_m))
	return &TableElementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TableElementClient) UpdateOneID(id uuid.UUID) *TableElementUpdateOne {
	mutation := newTableElementMutation(c.config, OpUpdateOne, withTableElementID(id))
	return &TableElementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TableElement.
func (c *TableElementClient) Delete() *TableElementDelete {
	mutation := newTableElementMutation(c.config, OpDelete)
	return &TableElementDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TableElementClient) DeleteOne(_m *TableElement) *TableElementDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TableElementClient) DeleteOneID(id uuid.UUID) *TableElementDeleteOne {
	builder := c.Delete().Where(tableelement.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TableElementDeleteOne{builder}
}

// Query returns a query builder for TableElement.
func (c *TableElementClient) Query() *TableElementQuery {
	return &TableElementQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTableElement},
		inters: c.Interceptors(),
	}
}

// Get returns a TableElement entity by its id.
func (c *TableElementClient) Get(ctx context.Context, id uuid.UUID) (*TableElement, error) {
	return c.Query().Where(tableelement.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TableElementClient) GetX(ctx context.Context, id uuid.UUID) *TableElement {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMap queries the map edge of a TableElement.
func (c *TableElementClient) QueryMap(_m *TableElement) *ContestAreaMapQuery {
	query := (&ContestAreaMapClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tableelement.Table, tableelement.FieldID, id),
			sqlgraph.To(contestareamap.Table, contestareamap.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tableelement.MapTable, tableelement.MapColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryStation queries the station edge of a TableElement.
func (c *TableElementClient) QueryStation(_m *TableElement) *StationQuery {
	query := (&StationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tableelement.Table, tableelement.FieldID, id),
			sqlgraph.To(station.Table, station.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, tableelement.StationTable, tableelement.StationColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TableElementClient) Hooks() []Hook {
	return c.hooks.TableElement
}

// Interceptors returns the client interceptors.
func (c *TableElementClient) Interceptors() []Interceptor {
	return c.inters.TableElement
}

func (c *TableElementClient) mutate(ctx context.Context, m *TableElementMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TableElementCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TableElementUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TableElementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TableElementDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TableElement mutation op: %q", m.Op())
	}
}

// TeamClient is a client for the Team schema.
type TeamClient struct {
	config
}

// NewTeamClient returns a client for the Team from the given config.
func NewTeamClient(c config) *TeamClient {
	return &TeamClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `team.Hooks(f(g(h())))`.
func (c *TeamClient) Use(hooks ...Hook) {
	c.hooks.Team = append(c.hooks.Team, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `team.Intercept(f(g(h())))`.
func (c *TeamClient) Intercept(interceptors ...Interceptor) {
	c.inters.Team = append(c.inters.Team, interceptors...)
}

// Create returns a builder for creating a Team entity.
func (c *TeamClient) Create() *TeamCreate {
	mutation := newTeamMutation(c.config, OpCreate)
	return &TeamCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Team entities.
func (c *TeamClient) CreateBulk(builders ...*TeamCreate) *TeamCreateBulk {
	return &TeamCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TeamClient) MapCreateBulk(slice any, setFunc func(*TeamCreate, int)) *TeamCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TeamCreateBulk{err: fmt.Errorf("calling to TeamClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TeamCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TeamCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Team.
func (c *TeamClient) Update() *TeamUpdate {
	mutation := newTeamMutation(c.config, OpUpdate)
	return &TeamUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TeamClient) UpdateOne(_m *Team) *TeamUpdateOne {
	mutation := newTeamMutation(c.config, OpUpdateOne, withTeam(_m))
	return &TeamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TeamClient) UpdateOneID(id string) *TeamUpdateOne {
	mutation := newTeamMutation(c.config, OpUpdateOne, withTeamID(id))
	return &TeamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Team.
func (c *TeamClient) Delete() *TeamDelete {
	mutation := newTeamMutation(c.config, OpDelete)
	return &TeamDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TeamClient) DeleteOne(_m *Team) *TeamDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TeamClient) DeleteOneID(id string) *TeamDeleteOne {
	builder := c.Delete().Where(team.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TeamDeleteOne{builder}
}

// Query returns a query builder for Team.
func (c *TeamClient) Query() *TeamQuery {
	return &TeamQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTeam},
		inters: c.Interceptors(),
	}
}

// Get returns a Team entity by its id.
func (c *TeamClient) Get(ctx context.Context, id string) (*Team, error) {
	return c.Query().Where(team.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TeamClient) GetX(ctx context.Context, id string) *Team {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryStation queries the station edge of a Team.
func (c *TeamClient) QueryStation(_m *Team) *StationQuery {
	query := (&StationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(team.Table, team.FieldID, id),
			sqlgraph.To(station.Table, station.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, team.StationTable, team.StationColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryContests queries the contests edge of a Team.
func (c *TeamClient) QueryContests(_m *Team) *ContestQuery {
	query := (&ContestClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(team.Table, team.FieldID, id),
			sqlgraph.To(contest.Table, contest.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, team.ContestsTable, team.ContestsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TeamClient) Hooks() []Hook {
	return c.hooks.Team
}

// Interceptors returns the client interceptors.
func (c *TeamClient) Interceptors() []Interceptor {
	return c.inters.Team
}

func (c *TeamClient) mutate(ctx context.Context, m *TeamMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TeamCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TeamUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TeamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TeamDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Team mutation op: %q", m.Op())
	}
}

// WallElementClient is a client for the WallElement schema.
type WallElementClient struct {
	config
}

// NewWallElementClient returns a client for the WallElement from the given config.
func NewWallElementClient(c config) *WallElementClient {
	return &WallElementClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `wallelement.Hooks(f(g(h())))`.
func (c *WallElementClient) Use(hooks ...Hook) {
	c.hooks.WallElement = append(c.hooks.WallElement, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `wallelement.Intercept(f(g(h())))`.
func (c *WallElementClient) Intercept(interceptors ...Interceptor) {
	c.inters.WallElement = append(c.inters.WallElement, interceptors...)
}

// Create returns a builder for creating a WallElement entity.
func (c *WallElementClient) Create() *WallElementCreate {
	mutation := newWallElementMutation(c.config, OpCreate)
	return &WallElementCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WallElement entities.
func (c *WallElementClient) CreateBulk(builders ...*WallElementCreate) *WallElementCreateBulk {
	return &WallElementCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WallElementClient) MapCreateBulk(slice any, setFunc func(*WallElementCreate, int)) *WallElementCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WallElementCreateBulk{err: fmt.Errorf("calling to WallElementClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WallElementCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WallElementCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WallElement.
func (c *WallElementClient) Update() *WallElementUpdate {
	mutation := newWallElementMutation(c.config, OpUpdate)
	return &WallElementUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WallElementClient) UpdateOne(_m *WallElement) *WallElementUpdateOne {
	mutation := newWallElementMutation(c.config, OpUpdateOne, withWallElement(_m))
	return &WallElementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WallElementClient) UpdateOneID(id uuid.UUID) *WallElementUpdateOne {
	mutation := newWallElementMutation(c.config, OpUpdateOne, withWallElementID(id))
	return &WallElementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WallElement.
func (c *WallElementClient) Delete() *WallElementDelete {
	mutation := newWallElementMutation(c.config, OpDelete)
	return &WallElementDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WallElementClient) DeleteOne(_m *WallElement) *WallElementDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WallElementClient) DeleteOneID(id uuid.UUID) *WallElementDeleteOne {
	builder := c.Delete().Where(wallelement.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WallElementDeleteOne{builder}
}

// Query returns a query builder for WallElement.
func (c *WallElementClient) Query() *WallElementQuery {
	return &WallElementQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWallElement},
		inters: c.Interceptors(),
	}
}

// Get returns a WallElement entity by its id.
func (c *WallElementClient) Get(ctx context.Context, id uuid.UUID) (*WallElement, error) {
	return c.Query().Where(wallelement.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WallElementClient) GetX(ctx context.Context, id uuid.UUID) *WallElement {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMap queries the map edge of a WallElement.
func (c *WallElementClient) QueryMap(_m *WallElement) *ContestAreaMapQuery {
	query := (&ContestAreaMapClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(wallelement.Table, wallelement.FieldID, id),
			sqlgraph.To(contestareamap.Table, contestareamap.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, wallelement.MapTable, wallelement.MapColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *WallElementClient) Hooks() []Hook {
	return c.hooks.WallElement
}

// Interceptors returns the client interceptors.
func (c *WallElementClient) Interceptors() []Interceptor {
	return c.inters.WallElement
}

func (c *WallElementClient) mutate(ctx context.Context, m *WallElementMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WallElementCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WallElementUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WallElementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WallElementDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WallElement mutation op: %q", m.Op())
	}
}

// WallpaperClient is a client for the Wallpaper schema.
type WallpaperClient struct {
	config
}

// NewWallpaperClient returns a client for the Wallpaper from the given config.
func NewWallpaperClient(c config) *WallpaperClient {
	return &WallpaperClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `wallpaper.Hooks(f(g(h())))`.
func (c *WallpaperClient) Use(hooks ...Hook) {
	c.hooks.Wallpaper = append(c.hooks.Wallpaper, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `wallpaper.Intercept(f(g(h())))`.
func (c *WallpaperClient) Intercept(interceptors ...Interceptor) {
	c.inters.Wallpaper = append(c.inters.Wallpaper, interceptors...)
}

// Create returns a builder for creating a Wallpaper entity.
func (c *WallpaperClient) Create() *WallpaperCreate {
	mutation := newWallpaperMutation(c.config, OpCreate)
	return &WallpaperCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Wallpaper entities.
func (c *WallpaperClient) CreateBulk(builders ...*WallpaperCreate) *WallpaperCreateBulk {
	return &WallpaperCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WallpaperClient) MapCreateBulk(slice any, setFunc func(*WallpaperCreate, int)) *WallpaperCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WallpaperCreateBulk{err: fmt.Errorf("calling to WallpaperClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WallpaperCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WallpaperCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Wallpaper.
func (c *WallpaperClient) Update() *WallpaperUpdate {
	mutation := newWallpaperMutation(c.config, OpUpdate)
	return &WallpaperUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WallpaperClient) UpdateOne(_m *Wallpaper) *WallpaperUpdateOne {
	mutation := newWallpaperMutation(c.config, OpUpdateOne, withWallpaper(_m))
	return &WallpaperUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WallpaperClient) UpdateOneID(id int) *WallpaperUpdateOne {
	mutation := newWallpaperMutation(c.config, OpUpdateOne, withWallpaperID(id))
	return &WallpaperUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Wallpaper.
func (c *WallpaperClient) Delete() *WallpaperDelete {
	mutation := newWallpaperMutation(c.config, OpDelete)
	return &WallpaperDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WallpaperClient) DeleteOne(_m *Wallpaper) *WallpaperDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WallpaperClient) DeleteOneID(id int) *WallpaperDeleteOne {
	builder := c.Delete().Where(wallpaper.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WallpaperDeleteOne{builder}
}

// Query returns a query builder for Wallpaper.
func (c *WallpaperClient) Query() *WallpaperQuery {
	return &WallpaperQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWallpaper},
		inters: c.Interceptors(),
	}
}

// Get returns a Wallpaper entity by its id.
func (c *WallpaperClient) Get(ctx context.Context, id int) (*Wallpaper, error) {
	return c.Query().Where(wallpaper.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WallpaperClient) GetX(ctx context.Context, id int) *Wallpaper {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *WallpaperClient) Hooks() []Hook {
	return c.hooks.Wallpaper
}

// Interceptors returns the client interceptors.
func (c *WallpaperClient) Interceptors() []Interceptor {
	return c.inters.Wallpaper
}

func (c *WallpaperClient) mutate(ctx context.Context, m *WallpaperMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WallpaperCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WallpaperUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WallpaperUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WallpaperDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Wallpaper mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Contest, ContestAreaMap, ContestMap, DoorElement, Station, TableElement, Team,
		WallElement, Wallpaper []ent.Hook
	}
	inters struct {
		Contest, ContestAreaMap, ContestMap, DoorElement, Station, TableElement, Team,
		WallElement, Wallpaper []ent.Interceptor
	}
)
