// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/contestareamap"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/predicate"
)

// ContestAreaMapDelete is the builder for deleting a ContestAreaMap entity.
type ContestAreaMapDelete struct {
	config
	hooks    []Hook
	mutation *ContestAreaMapMutation
}

// Where appends a list predicates to the ContestAreaMapDelete builder.
func (_d *ContestAreaMapDelete) Where(ps ...predicate.ContestAreaMap) *ContestAreaMapDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ContestAreaMapDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ContestAreaMapDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ContestAreaMapDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(contestareamap.Table, sqlgraph.NewFieldSpec(contestareamap.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ContestAreaMapDeleteOne is the builder for deleting a single ContestAreaMap entity.
type ContestAreaMapDeleteOne struct {
	_d *ContestAreaMapDelete
}

// Where appends a list predicates to the ContestAreaMapDelete builder.
func (_d *ContestAreaMapDeleteOne) Where(ps ...predicate.ContestAreaMap) *ContestAreaMapDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ContestAreaMapDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{contestareamap.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ContestAreaMapDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
