// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/contestmap"
)

// ContestMapCreate is the builder for creating a ContestMap entity.
type ContestMapCreate struct {
	config
	mutation *ContestMapMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetContestID sets the "contest_id" field.
func (_c *ContestMapCreate) SetContestID(v string) *ContestMapCreate {
	_c.mutation.SetContestID(v)
	return _c
}

// SetMapID sets the "map_id" field.
func (_c *ContestMapCreate) SetMapID(v int) *ContestMapCreate {
	_c.mutation.SetMapID(v)
	return _c
}

// Mutation returns the ContestMapMutation object of the builder.
func (_c *ContestMapCreate) Mutation() *ContestMapMutation {
	return _c.mutation
}

// Save creates the ContestMap in the database.
func (_c *ContestMapCreate) Save(ctx context.Context) (*ContestMap, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContestMapCreate) SaveX(ctx context.Context) *ContestMap {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContestMapCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContestMapCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContestMapCreate) check() error {
	if _, ok := _c.mutation.ContestID(); !ok {
		return &ValidationError{Name: "contest_id", err: errors.New(`ent: missing required field "ContestMap.contest_id"`)}
	}
	if _, ok := _c.mutation.MapID(); !ok {
		return &ValidationError{Name: "map_id", err: errors.New(`ent: missing required field "ContestMap.map_id"`)}
	}
	return nil
}

func (_c *ContestMapCreate) sqlSave(ctx context.Context) (*ContestMap, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContestMapCreate) createSpec() (*ContestMap, *sqlgraph.CreateSpec) {
	var (
		_node = &ContestMap{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contestmap.Table, sqlgraph.NewFieldSpec(contestmap.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ContestID(); ok {
		_spec.SetField(contestmap.FieldContestID, field.TypeString, value)
		_node.ContestID = value
	}
	if value, ok := _c.mutation.MapID(); ok {
		_spec.SetField(contestmap.FieldMapID, field.TypeInt, value)
		_node.MapID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContestMap.Create().
//		SetContestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContestMapUpsert) {
//			SetContestID(v+v).
//		}).
//		Exec(ctx)
func (_c *ContestMapCreate) OnConflict(opts ...sql.ConflictOption) *ContestMapUpsertOne {
	_c.conflict = opts
	return &ContestMapUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContestMap.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContestMapCreate) OnConflictColumns(columns ...string) *ContestMapUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContestMapUpsertOne{
		create: _c,
	}
}

type (
	// ContestMapUpsertOne is the builder for "upsert"-ing
	//  one ContestMap node.
	ContestMapUpsertOne struct {
		create *ContestMapCreate
	}

	// ContestMapUpsert is the "OnConflict" setter.
	ContestMapUpsert struct {
		*sql.UpdateSet
	}
)

// SetMapID sets the "map_id" field.
func (u *ContestMapUpsert) SetMapID(v int) *ContestMapUpsert {
	u.Set(contestmap.FieldMapID, v)
	return u
}

// UpdateMapID sets the "map_id" field to the value that was provided on create.
func (u *ContestMapUpsert) UpdateMapID() *ContestMapUpsert {
	u.SetExcluded(contestmap.FieldMapID)
	return u
}

// AddMapID adds v to the "map_id" field.
func (u *ContestMapUpsert) AddMapID(v int) *ContestMapUpsert {
	u.Add(contestmap.FieldMapID, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ContestMap.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ContestMapUpsertOne) UpdateNewValues() *ContestMapUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ContestID(); exists {
			s.SetIgnore(contestmap.FieldContestID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContestMap.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ContestMapUpsertOne) Ignore() *ContestMapUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContestMapUpsertOne) DoNothing() *ContestMapUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContestMapCreate.OnConflict
// documentation for more info.
func (u *ContestMapUpsertOne) Update(set func(*ContestMapUpsert)) *ContestMapUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContestMapUpsert{UpdateSet: update})
	}))
	return u
}

// SetMapID sets the "map_id" field.
func (u *ContestMapUpsertOne) SetMapID(v int) *ContestMapUpsertOne {
	return u.Update(func(s *ContestMapUpsert) {
		s.SetMapID(v)
	})
}

// AddMapID adds v to the "map_id" field.
func (u *ContestMapUpsertOne) AddMapID(v int) *ContestMapUpsertOne {
	return u.Update(func(s *ContestMapUpsert) {
		s.AddMapID(v)
	})
}

// UpdateMapID sets the "map_id" field to the value that was provided on create.
func (u *ContestMapUpsertOne) UpdateMapID() *ContestMapUpsertOne {
	return u.Update(func(s *ContestMapUpsert) {
		s.UpdateMapID()
	})
}

// Exec executes the query.
func (u *ContestMapUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ContestMapCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContestMapUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ContestMapUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ContestMapUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ContestMapCreateBulk is the builder for creating many ContestMap entities in bulk.
type ContestMapCreateBulk struct {
	config
	err      error
	builders []*ContestMapCreate
	conflict []sql.ConflictOption
}

// Save creates the ContestMap entities in the database.
func (_c *ContestMapCreateBulk) Save(ctx context.Context) ([]*ContestMap, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContestMap, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContestMapMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContestMapCreateBulk) SaveX(ctx context.Context) []*ContestMap {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContestMapCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContestMapCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContestMap.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContestMapUpsert) {
//			SetContestID(v+v).
//		}).
//		Exec(ctx)
func (_c *ContestMapCreateBulk) OnConflict(opts ...sql.ConflictOption) *ContestMapUpsertBulk {
	_c.conflict = opts
	return &ContestMapUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContestMap.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContestMapCreateBulk) OnConflictColumns(columns ...string) *ContestMapUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContestMapUpsertBulk{
		create: _c,
	}
}

// ContestMapUpsertBulk is the builder for "upsert"-ing
// a bulk of ContestMap nodes.
type ContestMapUpsertBulk struct {
	create *ContestMapCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ContestMap.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ContestMapUpsertBulk) UpdateNewValues() *ContestMapUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ContestID(); exists {
				s.SetIgnore(contestmap.FieldContestID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContestMap.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ContestMapUpsertBulk) Ignore() *ContestMapUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContestMapUpsertBulk) DoNothing() *ContestMapUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContestMapCreateBulk.OnConflict
// documentation for more info.
func (u *ContestMapUpsertBulk) Update(set func(*ContestMapUpsert)) *ContestMapUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContestMapUpsert{UpdateSet: update})
	}))
	return u
}

// SetMapID sets the "map_id" field.
func (u *ContestMapUpsertBulk) SetMapID(v int) *ContestMapUpsertBulk {
	return u.Update(func(s *ContestMapUpsert) {
		s.SetMapID(v)
	})
}

// AddMapID adds v to the "map_id" field.
func (u *ContestMapUpsertBulk) AddMapID(v int) *ContestMapUpsertBulk {
	return u.Update(func(s *ContestMapUpsert) {
		s.AddMapID(v)
	})
}

// UpdateMapID sets the "map_id" field to the value that was provided on create.
func (u *ContestMapUpsertBulk) UpdateMapID() *ContestMapUpsertBulk {
	return u.Update(func(s *ContestMapUpsert) {
		s.UpdateMapID()
	})
}

// Exec executes the query.
func (u *ContestMapUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ContestMapCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ContestMapCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContestMapUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
