// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/contestmap"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/predicate"
)

// ContestMapUpdate is the builder for updating ContestMap entities.
type ContestMapUpdate struct {
	config
	hooks    []Hook
	mutation *ContestMapMutation
}

// Where appends a list predicates to the ContestMapUpdate builder.
func (_u *ContestMapUpdate) Where(ps ...predicate.ContestMap) *ContestMapUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMapID sets the "map_id" field.
func (_u *ContestMapUpdate) SetMapID(v int) *ContestMapUpdate {
	_u.mutation.ResetMapID()
	_u.mutation.SetMapID(v)
	return _u
}

// SetNillableMapID sets the "map_id" field if the given value is not nil.
func (_u *ContestMapUpdate) SetNillableMapID(v *int) *ContestMapUpdate {
	if v != nil {
		_u.SetMapID(*v)
	}
	return _u
}

// AddMapID adds value to the "map_id" field.
func (_u *ContestMapUpdate) AddMapID(v int) *ContestMapUpdate {
	_u.mutation.AddMapID(v)
	return _u
}

// Mutation returns the ContestMapMutation object of the builder.
func (_u *ContestMapUpdate) Mutation() *ContestMapMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ContestMapUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContestMapUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ContestMapUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContestMapUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ContestMapUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(contestmap.Table, contestmap.Columns, sqlgraph.NewFieldSpec(contestmap.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MapID(); ok {
		_spec.SetField(contestmap.FieldMapID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMapID(); ok {
		_spec.AddField(contestmap.FieldMapID, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contestmap.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ContestMapUpdateOne is the builder for updating a single ContestMap entity.
type ContestMapUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ContestMapMutation
}

// SetMapID sets the "map_id" field.
func (_u *ContestMapUpdateOne) SetMapID(v int) *ContestMapUpdateOne {
	_u.mutation.ResetMapID()
	_u.mutation.SetMapID(v)
	return _u
}

// SetNillableMapID sets the "map_id" field if the given value is not nil.
func (_u *ContestMapUpdateOne) SetNillableMapID(v *int) *ContestMapUpdateOne {
	if v != nil {
		_u.SetMapID(*v)
	}
	return _u
}

// AddMapID adds value to the "map_id" field.
func (_u *ContestMapUpdateOne) AddMapID(v int) *ContestMapUpdateOne {
	_u.mutation.AddMapID(v)
	return _u
}

// Mutation returns the ContestMapMutation object of the builder.
func (_u *ContestMapUpdateOne) Mutation() *ContestMapMutation {
	return _u.mutation
}

// Where appends a list predicates to the ContestMapUpdate builder.
func (_u *ContestMapUpdateOne) Where(ps ...predicate.ContestMap) *ContestMapUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ContestMapUpdateOne) Select(field string, fields ...string) *ContestMapUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ContestMap entity.
func (_u *ContestMapUpdateOne) Save(ctx context.Context) (*ContestMap, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContestMapUpdateOne) SaveX(ctx context.Context) *ContestMap {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ContestMapUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContestMapUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ContestMapUpdateOne) sqlSave(ctx context.Context) (_node *ContestMap, err error) {
	_spec := sqlgraph.NewUpdateSpec(contestmap.Table, contestmap.Columns, sqlgraph.NewFieldSpec(contestmap.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ContestMap.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contestmap.FieldID)
		for _, f := range fields {
			if !contestmap.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != contestmap.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MapID(); ok {
		_spec.SetField(contestmap.FieldMapID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMapID(); ok {
		_spec.AddField(contestmap.FieldMapID, field.TypeInt, value)
	}
	_node = &ContestMap{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contestmap.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
