// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/contestareamap"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/doorelement"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/predicate"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/tableelement"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/wallelement"
)

// ContestAreaMapQuery is the builder for querying ContestAreaMap entities.
type ContestAreaMapQuery struct {
	config
	ctx        *QueryContext
	order      []contestareamap.OrderOption
	inters     []Interceptor
	predicates []predicate.ContestAreaMap
	withDoors  *DoorElementQuery
	withWalls  *WallElementQuery
	withTables *TableElementQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ContestAreaMapQuery builder.
func (_q *ContestAreaMapQuery) Where(ps ...predicate.ContestAreaMap) *ContestAreaMapQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ContestAreaMapQuery) Limit(limit int) *ContestAreaMapQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ContestAreaMapQuery) Offset(offset int) *ContestAreaMapQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ContestAreaMapQuery) Unique(unique bool) *ContestAreaMapQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ContestAreaMapQuery) Order(o ...contestareamap.OrderOption) *ContestAreaMapQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDoors chains the current query on the "doors" edge.
func (_q *ContestAreaMapQuery) QueryDoors() *DoorElementQuery {
	query := (&DoorElementClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contestareamap.Table, contestareamap.FieldID, selector),
			sqlgraph.To(doorelement.Table, doorelement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contestareamap.DoorsTable, contestareamap.DoorsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWalls chains the current query on the "walls" edge.
func (_q *ContestAreaMapQuery) QueryWalls() *WallElementQuery {
	query := (&WallElementClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contestareamap.Table, contestareamap.FieldID, selector),
			sqlgraph.To(wallelement.Table, wallelement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contestareamap.WallsTable, contestareamap.WallsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTables chains the current query on the "tables" edge.
func (_q *ContestAreaMapQuery) QueryTables() *TableElementQuery {
	query := (&TableElementClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contestareamap.Table, contestareamap.FieldID, selector),
			sqlgraph.To(tableelement.Table, tableelement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, contestareamap.TablesTable, contestareamap.TablesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ContestAreaMap entity from the query.
// Returns a *NotFoundError when no ContestAreaMap was found.
func (_q *ContestAreaMapQuery) First(ctx context.Context) (*ContestAreaMap, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{contestareamap.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ContestAreaMapQuery) FirstX(ctx context.Context) *ContestAreaMap {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ContestAreaMap ID from the query.
// Returns a *NotFoundError when no ContestAreaMap ID was found.
func (_q *ContestAreaMapQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{contestareamap.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ContestAreaMapQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ContestAreaMap entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ContestAreaMap entity is found.
// Returns a *NotFoundError when no ContestAreaMap entities are found.
func (_q *ContestAreaMapQuery) Only(ctx context.Context) (*ContestAreaMap, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{contestareamap.Label}
	default:
		return nil, &NotSingularError{contestareamap.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ContestAreaMapQuery) OnlyX(ctx context.Context) *ContestAreaMap {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ContestAreaMap ID in the query.
// Returns a *NotSingularError when more than one ContestAreaMap ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ContestAreaMapQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{contestareamap.Label}
	default:
		err = &NotSingularError{contestareamap.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ContestAreaMapQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ContestAreaMaps.
func (_q *ContestAreaMapQuery) All(ctx context.Context) ([]*ContestAreaMap, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ContestAreaMap, *ContestAreaMapQuery]()
	return withInterceptors[[]*ContestAreaMap](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ContestAreaMapQuery) AllX(ctx context.Context) []*ContestAreaMap {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ContestAreaMap IDs.
func (_q *ContestAreaMapQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(contestareamap.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ContestAreaMapQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ContestAreaMapQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ContestAreaMapQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ContestAreaMapQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ContestAreaMapQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ContestAreaMapQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ContestAreaMapQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ContestAreaMapQuery) Clone() *ContestAreaMapQuery {
	if _q == nil {
		return nil
	}
	return &ContestAreaMapQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]contestareamap.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.ContestAreaMap{}, _q.predicates...),
		withDoors:  _q.withDoors.Clone(),
		withWalls:  _q.withWalls.Clone(),
		withTables: _q.withTables.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithDoors tells the query-builder to eager-load the nodes that are connected to
// the "doors" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContestAreaMapQuery) WithDoors(opts ...func(*DoorElementQuery)) *ContestAreaMapQuery {
	query := (&DoorElementClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDoors = query
	return _q
}

// WithWalls tells the query-builder to eager-load the nodes that are connected to
// the "walls" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContestAreaMapQuery) WithWalls(opts ...func(*WallElementQuery)) *ContestAreaMapQuery {
	query := (&WallElementClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWalls = query
	return _q
}

// WithTables tells the query-builder to eager-load the nodes that are connected to
// the "tables" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ContestAreaMapQuery) WithTables(opts ...func(*TableElementQuery)) *ContestAreaMapQuery {
	query := (&TableElementClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTables = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ContestAreaMap.Query().
//		GroupBy(contestareamap.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ContestAreaMapQuery) GroupBy(field string, fields ...string) *ContestAreaMapGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ContestAreaMapGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = contestareamap.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//	}
//
//	client.ContestAreaMap.Query().
//		Select(contestareamap.FieldName).
//		Scan(ctx, &v)
func (_q *ContestAreaMapQuery) Select(fields ...string) *ContestAreaMapSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ContestAreaMapSelect{ContestAreaMapQuery: _q}
	sbuild.label = contestareamap.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ContestAreaMapSelect configured with the given aggregations.
func (_q *ContestAreaMapQuery) Aggregate(fns ...AggregateFunc) *ContestAreaMapSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ContestAreaMapQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !contestareamap.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ContestAreaMapQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ContestAreaMap, error) {
	var (
		nodes       = []*ContestAreaMap{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withDoors != nil,
			_q.withWalls != nil,
			_q.withTables != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ContestAreaMap).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ContestAreaMap{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDoors; query != nil {
		if err := _q.loadDoors(ctx, query, nodes,
			func(n *ContestAreaMap) { n.Edges.Doors = []*DoorElement{} },
			func(n *ContestAreaMap, e *DoorElement) { n.Edges.Doors = append(n.Edges.Doors, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWalls; query != nil {
		if err := _q.loadWalls(ctx, query, nodes,
			func(n *ContestAreaMap) { n.Edges.Walls = []*WallElement{} },
			func(n *ContestAreaMap, e *WallElement) { n.Edges.Walls = append(n.Edges.Walls, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTables; query != nil {
		if err := _q.loadTables(ctx, query, nodes,
			func(n *ContestAreaMap) { n.Edges.Tables = []*TableElement{} },
			func(n *ContestAreaMap, e *TableElement) { n.Edges.Tables = append(n.Edges.Tables, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ContestAreaMapQuery) loadDoors(ctx context.Context, query *DoorElementQuery, nodes []*ContestAreaMap, init func(*ContestAreaMap), assign func(*ContestAreaMap, *DoorElement)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ContestAreaMap)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.DoorElement(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contestareamap.DoorsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.contest_area_map_doors
		if fk == nil {
			return fmt.Errorf(`foreign-key "contest_area_map_doors" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "contest_area_map_doors" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ContestAreaMapQuery) loadWalls(ctx context.Context, query *WallElementQuery, nodes []*ContestAreaMap, init func(*ContestAreaMap), assign func(*ContestAreaMap, *WallElement)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ContestAreaMap)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.WallElement(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contestareamap.WallsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.contest_area_map_walls
		if fk == nil {
			return fmt.Errorf(`foreign-key "contest_area_map_walls" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "contest_area_map_walls" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ContestAreaMapQuery) loadTables(ctx context.Context, query *TableElementQuery, nodes []*ContestAreaMap, init func(*ContestAreaMap), assign func(*ContestAreaMap, *TableElement)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ContestAreaMap)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.TableElement(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(contestareamap.TablesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.contest_area_map_tables
		if fk == nil {
			return fmt.Errorf(`foreign-key "contest_area_map_tables" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "contest_area_map_tables" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ContestAreaMapQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ContestAreaMapQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(contestareamap.Table, contestareamap.Columns, sqlgraph.NewFieldSpec(contestareamap.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contestareamap.FieldID)
		for i := range fields {
			if fields[i] != contestareamap.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ContestAreaMapQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(contestareamap.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = contestareamap.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ContestAreaMapGroupBy is the group-by builder for ContestAreaMap entities.
type ContestAreaMapGroupBy struct {
	selector
	build *ContestAreaMapQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ContestAreaMapGroupBy) Aggregate(fns ...AggregateFunc) *ContestAreaMapGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ContestAreaMapGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContestAreaMapQuery, *ContestAreaMapGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ContestAreaMapGroupBy) sqlScan(ctx context.Context, root *ContestAreaMapQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ContestAreaMapSelect is the builder for selecting fields of ContestAreaMap entities.
type ContestAreaMapSelect struct {
	*ContestAreaMapQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ContestAreaMapSelect) Aggregate(fns ...AggregateFunc) *ContestAreaMapSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ContestAreaMapSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContestAreaMapQuery, *ContestAreaMapSelect](ctx, _s.ContestAreaMapQuery, _s, _s.inters, v)
}

func (_s *ContestAreaMapSelect) sqlScan(ctx context.Context, root *ContestAreaMapQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
