// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/contestareamap"
)

// ContestAreaMap is the model entity for the ContestAreaMap schema.
type ContestAreaMap struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "Name" field.
	Name string `json:"Name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ContestAreaMapQuery when eager-loading is set.
	Edges        ContestAreaMapEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ContestAreaMapEdges holds the relations/edges for other nodes in the graph.
type ContestAreaMapEdges struct {
	// Doors holds the value of the doors edge.
	Doors []*DoorElement `json:"doors,omitempty"`
	// Walls holds the value of the walls edge.
	Walls []*WallElement `json:"walls,omitempty"`
	// Tables holds the value of the tables edge.
	Tables []*TableElement `json:"tables,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// DoorsOrErr returns the Doors value or an error if the edge
// was not loaded in eager-loading.
func (e ContestAreaMapEdges) DoorsOrErr() ([]*DoorElement, error) {
	if e.loadedTypes[0] {
		return e.Doors, nil
	}
	return nil, &NotLoadedError{edge: "doors"}
}

// WallsOrErr returns the Walls value or an error if the edge
// was not loaded in eager-loading.
func (e ContestAreaMapEdges) WallsOrErr() ([]*WallElement, error) {
	if e.loadedTypes[1] {
		return e.Walls, nil
	}
	return nil, &NotLoadedError{edge: "walls"}
}

// TablesOrErr returns the Tables value or an error if the edge
// was not loaded in eager-loading.
func (e ContestAreaMapEdges) TablesOrErr() ([]*TableElement, error) {
	if e.loadedTypes[2] {
		return e.Tables, nil
	}
	return nil, &NotLoadedError{edge: "tables"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContestAreaMap) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contestareamap.FieldID:
			values[i] = new(sql.NullInt64)
		case contestareamap.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContestAreaMap fields.
func (_m *ContestAreaMap) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contestareamap.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case contestareamap.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContestAreaMap.
// This includes values selected through modifiers, order, etc.
func (_m *ContestAreaMap) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDoors queries the "doors" edge of the ContestAreaMap entity.
func (_m *ContestAreaMap) QueryDoors() *DoorElementQuery {
	return NewContestAreaMapClient(_m.config).QueryDoors(_m)
}

// QueryWalls queries the "walls" edge of the ContestAreaMap entity.
func (_m *ContestAreaMap) QueryWalls() *WallElementQuery {
	return NewContestAreaMapClient(_m.config).QueryWalls(_m)
}

// QueryTables queries the "tables" edge of the ContestAreaMap entity.
func (_m *ContestAreaMap) QueryTables() *TableElementQuery {
	return NewContestAreaMapClient(_m.config).QueryTables(_m)
}

// Update returns a builder for updating this ContestAreaMap.
// Note that you need to call ContestAreaMap.Unwrap() before calling this method if this ContestAreaMap
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ContestAreaMap) Update() *ContestAreaMapUpdateOne {
	return NewContestAreaMapClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ContestAreaMap entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ContestAreaMap) Unwrap() *ContestAreaMap {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContestAreaMap is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ContestAreaMap) String() string {
	var builder strings.Builder
	builder.WriteString("ContestAreaMap(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("Name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// ContestAreaMaps is a parsable slice of ContestAreaMap.
type ContestAreaMaps []*ContestAreaMap
