// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/contestareamap"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/doorelement"
	"github.com/google/uuid"
)

// DoorElement is the model entity for the DoorElement schema.
type DoorElement struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// X holds the value of the "x" field.
	X int `json:"x,omitempty"`
	// Y holds the value of the "y" field.
	Y int `json:"y,omitempty"`
	// Rotation holds the value of the "rotation" field.
	Rotation doorelement.Rotation `json:"rotation,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DoorElementQuery when eager-loading is set.
	Edges                  DoorElementEdges `json:"edges"`
	contest_area_map_doors *int
	selectValues           sql.SelectValues
}

// DoorElementEdges holds the relations/edges for other nodes in the graph.
type DoorElementEdges struct {
	// Map holds the value of the map edge.
	Map *ContestAreaMap `json:"map,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MapOrErr returns the Map value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DoorElementEdges) MapOrErr() (*ContestAreaMap, error) {
	if e.Map != nil {
		return e.Map, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: contestareamap.Label}
	}
	return nil, &NotLoadedError{edge: "map"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DoorElement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case doorelement.FieldX, doorelement.FieldY:
			values[i] = new(sql.NullInt64)
		case doorelement.FieldRotation:
			values[i] = new(sql.NullString)
		case doorelement.FieldID:
			values[i] = new(uuid.UUID)
		case doorelement.ForeignKeys[0]: // contest_area_map_doors
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DoorElement fields.
func (_m *DoorElement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case doorelement.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case doorelement.FieldX:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field x", values[i])
			} else if value.Valid {
				_m.X = int(value.Int64)
			}
		case doorelement.FieldY:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field y", values[i])
			} else if value.Valid {
				_m.Y = int(value.Int64)
			}
		case doorelement.FieldRotation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rotation", values[i])
			} else if value.Valid {
				_m.Rotation = doorelement.Rotation(value.String)
			}
		case doorelement.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field contest_area_map_doors", value)
			} else if value.Valid {
				_m.contest_area_map_doors = new(int)
				*_m.contest_area_map_doors = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DoorElement.
// This includes values selected through modifiers, order, etc.
func (_m *DoorElement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMap queries the "map" edge of the DoorElement entity.
func (_m *DoorElement) QueryMap() *ContestAreaMapQuery {
	return NewDoorElementClient(_m.config).QueryMap(_m)
}

// Update returns a builder for updating this DoorElement.
// Note that you need to call DoorElement.Unwrap() before calling this method if this DoorElement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DoorElement) Update() *DoorElementUpdateOne {
	return NewDoorElementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DoorElement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DoorElement) Unwrap() *DoorElement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DoorElement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DoorElement) String() string {
	var builder strings.Builder
	builder.WriteString("DoorElement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("x=")
	builder.WriteString(fmt.Sprintf("%v", _m.X))
	builder.WriteString(", ")
	builder.WriteString("y=")
	builder.WriteString(fmt.Sprintf("%v", _m.Y))
	builder.WriteString(", ")
	builder.WriteString("rotation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rotation))
	builder.WriteByte(')')
	return builder.String()
}

// DoorElements is a parsable slice of DoorElement.
type DoorElements []*DoorElement
