// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/station"
)

// Station is the model entity for the Station schema.
type Station struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// IP holds the value of the "ip" field.
	IP string `json:"ip,omitempty"`
	// ConnectedAt holds the value of the "connected_at" field.
	ConnectedAt time.Time `json:"connected_at,omitempty"`
	// DisconnectedAt holds the value of the "disconnected_at" field.
	DisconnectedAt *time.Time `json:"disconnected_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StationQuery when eager-loading is set.
	Edges        StationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StationEdges holds the relations/edges for other nodes in the graph.
type StationEdges struct {
	// TableElement holds the value of the table_element edge.
	TableElement []*TableElement `json:"table_element,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TableElementOrErr returns the TableElement value or an error if the edge
// was not loaded in eager-loading.
func (e StationEdges) TableElementOrErr() ([]*TableElement, error) {
	if e.loadedTypes[0] {
		return e.TableElement, nil
	}
	return nil, &NotLoadedError{edge: "table_element"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Station) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case station.FieldID:
			values[i] = new(sql.NullInt64)
		case station.FieldIP:
			values[i] = new(sql.NullString)
		case station.FieldConnectedAt, station.FieldDisconnectedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Station fields.
func (_m *Station) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case station.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case station.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case station.FieldConnectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field connected_at", values[i])
			} else if value.Valid {
				_m.ConnectedAt = value.Time
			}
		case station.FieldDisconnectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field disconnected_at", values[i])
			} else if value.Valid {
				_m.DisconnectedAt = new(time.Time)
				*_m.DisconnectedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Station.
// This includes values selected through modifiers, order, etc.
func (_m *Station) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTableElement queries the "table_element" edge of the Station entity.
func (_m *Station) QueryTableElement() *TableElementQuery {
	return NewStationClient(_m.config).QueryTableElement(_m)
}

// Update returns a builder for updating this Station.
// Note that you need to call Station.Unwrap() before calling this method if this Station
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Station) Update() *StationUpdateOne {
	return NewStationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Station entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Station) Unwrap() *Station {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Station is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Station) String() string {
	var builder strings.Builder
	builder.WriteString("Station(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("connected_at=")
	builder.WriteString(_m.ConnectedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DisconnectedAt; v != nil {
		builder.WriteString("disconnected_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Stations is a parsable slice of Station.
type Stations []*Station
