// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/predicate"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/station"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/tableelement"
	"github.com/google/uuid"
)

// StationUpdate is the builder for updating Station entities.
type StationUpdate struct {
	config
	hooks    []Hook
	mutation *StationMutation
}

// Where appends a list predicates to the StationUpdate builder.
func (_u *StationUpdate) Where(ps ...predicate.Station) *StationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetConnectedAt sets the "connected_at" field.
func (_u *StationUpdate) SetConnectedAt(v time.Time) *StationUpdate {
	_u.mutation.SetConnectedAt(v)
	return _u
}

// SetNillableConnectedAt sets the "connected_at" field if the given value is not nil.
func (_u *StationUpdate) SetNillableConnectedAt(v *time.Time) *StationUpdate {
	if v != nil {
		_u.SetConnectedAt(*v)
	}
	return _u
}

// SetDisconnectedAt sets the "disconnected_at" field.
func (_u *StationUpdate) SetDisconnectedAt(v time.Time) *StationUpdate {
	_u.mutation.SetDisconnectedAt(v)
	return _u
}

// SetNillableDisconnectedAt sets the "disconnected_at" field if the given value is not nil.
func (_u *StationUpdate) SetNillableDisconnectedAt(v *time.Time) *StationUpdate {
	if v != nil {
		_u.SetDisconnectedAt(*v)
	}
	return _u
}

// ClearDisconnectedAt clears the value of the "disconnected_at" field.
func (_u *StationUpdate) ClearDisconnectedAt() *StationUpdate {
	_u.mutation.ClearDisconnectedAt()
	return _u
}

// AddTableElementIDs adds the "table_element" edge to the TableElement entity by IDs.
func (_u *StationUpdate) AddTableElementIDs(ids ...uuid.UUID) *StationUpdate {
	_u.mutation.AddTableElementIDs(ids...)
	return _u
}

// AddTableElement adds the "table_element" edges to the TableElement entity.
func (_u *StationUpdate) AddTableElement(v ...*TableElement) *StationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTableElementIDs(ids...)
}

// Mutation returns the StationMutation object of the builder.
func (_u *StationUpdate) Mutation() *StationMutation {
	return _u.mutation
}

// ClearTableElement clears all "table_element" edges to the TableElement entity.
func (_u *StationUpdate) ClearTableElement() *StationUpdate {
	_u.mutation.ClearTableElement()
	return _u
}

// RemoveTableElementIDs removes the "table_element" edge to TableElement entities by IDs.
func (_u *StationUpdate) RemoveTableElementIDs(ids ...uuid.UUID) *StationUpdate {
	_u.mutation.RemoveTableElementIDs(ids...)
	return _u
}

// RemoveTableElement removes "table_element" edges to TableElement entities.
func (_u *StationUpdate) RemoveTableElement(v ...*TableElement) *StationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTableElementIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *StationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(station.Table, station.Columns, sqlgraph.NewFieldSpec(station.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ConnectedAt(); ok {
		_spec.SetField(station.FieldConnectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DisconnectedAt(); ok {
		_spec.SetField(station.FieldDisconnectedAt, field.TypeTime, value)
	}
	if _u.mutation.DisconnectedAtCleared() {
		_spec.ClearField(station.FieldDisconnectedAt, field.TypeTime)
	}
	if _u.mutation.TableElementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   station.TableElementTable,
			Columns: []string{station.TableElementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tableelement.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTableElementIDs(); len(nodes) > 0 && !_u.mutation.TableElementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   station.TableElementTable,
			Columns: []string{station.TableElementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tableelement.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TableElementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   station.TableElementTable,
			Columns: []string{station.TableElementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tableelement.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{station.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StationUpdateOne is the builder for updating a single Station entity.
type StationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StationMutation
}

// SetConnectedAt sets the "connected_at" field.
func (_u *StationUpdateOne) SetConnectedAt(v time.Time) *StationUpdateOne {
	_u.mutation.SetConnectedAt(v)
	return _u
}

// SetNillableConnectedAt sets the "connected_at" field if the given value is not nil.
func (_u *StationUpdateOne) SetNillableConnectedAt(v *time.Time) *StationUpdateOne {
	if v != nil {
		_u.SetConnectedAt(*v)
	}
	return _u
}

// SetDisconnectedAt sets the "disconnected_at" field.
func (_u *StationUpdateOne) SetDisconnectedAt(v time.Time) *StationUpdateOne {
	_u.mutation.SetDisconnectedAt(v)
	return _u
}

// SetNillableDisconnectedAt sets the "disconnected_at" field if the given value is not nil.
func (_u *StationUpdateOne) SetNillableDisconnectedAt(v *time.Time) *StationUpdateOne {
	if v != nil {
		_u.SetDisconnectedAt(*v)
	}
	return _u
}

// ClearDisconnectedAt clears the value of the "disconnected_at" field.
func (_u *StationUpdateOne) ClearDisconnectedAt() *StationUpdateOne {
	_u.mutation.ClearDisconnectedAt()
	return _u
}

// AddTableElementIDs adds the "table_element" edge to the TableElement entity by IDs.
func (_u *StationUpdateOne) AddTableElementIDs(ids ...uuid.UUID) *StationUpdateOne {
	_u.mutation.AddTableElementIDs(ids...)
	return _u
}

// AddTableElement adds the "table_element" edges to the TableElement entity.
func (_u *StationUpdateOne) AddTableElement(v ...*TableElement) *StationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTableElementIDs(ids...)
}

// Mutation returns the StationMutation object of the builder.
func (_u *StationUpdateOne) Mutation() *StationMutation {
	return _u.mutation
}

// ClearTableElement clears all "table_element" edges to the TableElement entity.
func (_u *StationUpdateOne) ClearTableElement() *StationUpdateOne {
	_u.mutation.ClearTableElement()
	return _u
}

// RemoveTableElementIDs removes the "table_element" edge to TableElement entities by IDs.
func (_u *StationUpdateOne) RemoveTableElementIDs(ids ...uuid.UUID) *StationUpdateOne {
	_u.mutation.RemoveTableElementIDs(ids...)
	return _u
}

// RemoveTableElement removes "table_element" edges to TableElement entities.
func (_u *StationUpdateOne) RemoveTableElement(v ...*TableElement) *StationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTableElementIDs(ids...)
}

// Where appends a list predicates to the StationUpdate builder.
func (_u *StationUpdateOne) Where(ps ...predicate.Station) *StationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StationUpdateOne) Select(field string, fields ...string) *StationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Station entity.
func (_u *StationUpdateOne) Save(ctx context.Context) (*Station, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StationUpdateOne) SaveX(ctx context.Context) *Station {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *StationUpdateOne) sqlSave(ctx context.Context) (_node *Station, err error) {
	_spec := sqlgraph.NewUpdateSpec(station.Table, station.Columns, sqlgraph.NewFieldSpec(station.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Station.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, station.FieldID)
		for _, f := range fields {
			if !station.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != station.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ConnectedAt(); ok {
		_spec.SetField(station.FieldConnectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DisconnectedAt(); ok {
		_spec.SetField(station.FieldDisconnectedAt, field.TypeTime, value)
	}
	if _u.mutation.DisconnectedAtCleared() {
		_spec.ClearField(station.FieldDisconnectedAt, field.TypeTime)
	}
	if _u.mutation.TableElementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   station.TableElementTable,
			Columns: []string{station.TableElementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tableelement.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTableElementIDs(); len(nodes) > 0 && !_u.mutation.TableElementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   station.TableElementTable,
			Columns: []string{station.TableElementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tableelement.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TableElementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   station.TableElementTable,
			Columns: []string{station.TableElementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tableelement.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Station{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{station.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
