// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/station"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/tableelement"
	"github.com/google/uuid"
)

// StationCreate is the builder for creating a Station entity.
type StationCreate struct {
	config
	mutation *StationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetIP sets the "ip" field.
func (_c *StationCreate) SetIP(v string) *StationCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetConnectedAt sets the "connected_at" field.
func (_c *StationCreate) SetConnectedAt(v time.Time) *StationCreate {
	_c.mutation.SetConnectedAt(v)
	return _c
}

// SetNillableConnectedAt sets the "connected_at" field if the given value is not nil.
func (_c *StationCreate) SetNillableConnectedAt(v *time.Time) *StationCreate {
	if v != nil {
		_c.SetConnectedAt(*v)
	}
	return _c
}

// SetDisconnectedAt sets the "disconnected_at" field.
func (_c *StationCreate) SetDisconnectedAt(v time.Time) *StationCreate {
	_c.mutation.SetDisconnectedAt(v)
	return _c
}

// SetNillableDisconnectedAt sets the "disconnected_at" field if the given value is not nil.
func (_c *StationCreate) SetNillableDisconnectedAt(v *time.Time) *StationCreate {
	if v != nil {
		_c.SetDisconnectedAt(*v)
	}
	return _c
}

// AddTableElementIDs adds the "table_element" edge to the TableElement entity by IDs.
func (_c *StationCreate) AddTableElementIDs(ids ...uuid.UUID) *StationCreate {
	_c.mutation.AddTableElementIDs(ids...)
	return _c
}

// AddTableElement adds the "table_element" edges to the TableElement entity.
func (_c *StationCreate) AddTableElement(v ...*TableElement) *StationCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTableElementIDs(ids...)
}

// Mutation returns the StationMutation object of the builder.
func (_c *StationCreate) Mutation() *StationMutation {
	return _c.mutation
}

// Save creates the Station in the database.
func (_c *StationCreate) Save(ctx context.Context) (*Station, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StationCreate) SaveX(ctx context.Context) *Station {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StationCreate) defaults() {
	if _, ok := _c.mutation.ConnectedAt(); !ok {
		v := station.DefaultConnectedAt
		_c.mutation.SetConnectedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StationCreate) check() error {
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "Station.ip"`)}
	}
	if _, ok := _c.mutation.ConnectedAt(); !ok {
		return &ValidationError{Name: "connected_at", err: errors.New(`ent: missing required field "Station.connected_at"`)}
	}
	return nil
}

func (_c *StationCreate) sqlSave(ctx context.Context) (*Station, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StationCreate) createSpec() (*Station, *sqlgraph.CreateSpec) {
	var (
		_node = &Station{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(station.Table, sqlgraph.NewFieldSpec(station.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(station.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.ConnectedAt(); ok {
		_spec.SetField(station.FieldConnectedAt, field.TypeTime, value)
		_node.ConnectedAt = value
	}
	if value, ok := _c.mutation.DisconnectedAt(); ok {
		_spec.SetField(station.FieldDisconnectedAt, field.TypeTime, value)
		_node.DisconnectedAt = &value
	}
	if nodes := _c.mutation.TableElementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   station.TableElementTable,
			Columns: []string{station.TableElementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tableelement.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Station.Create().
//		SetIP(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StationUpsert) {
//			SetIP(v+v).
//		}).
//		Exec(ctx)
func (_c *StationCreate) OnConflict(opts ...sql.ConflictOption) *StationUpsertOne {
	_c.conflict = opts
	return &StationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Station.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *StationCreate) OnConflictColumns(columns ...string) *StationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &StationUpsertOne{
		create: _c,
	}
}

type (
	// StationUpsertOne is the builder for "upsert"-ing
	//  one Station node.
	StationUpsertOne struct {
		create *StationCreate
	}

	// StationUpsert is the "OnConflict" setter.
	StationUpsert struct {
		*sql.UpdateSet
	}
)

// SetConnectedAt sets the "connected_at" field.
func (u *StationUpsert) SetConnectedAt(v time.Time) *StationUpsert {
	u.Set(station.FieldConnectedAt, v)
	return u
}

// UpdateConnectedAt sets the "connected_at" field to the value that was provided on create.
func (u *StationUpsert) UpdateConnectedAt() *StationUpsert {
	u.SetExcluded(station.FieldConnectedAt)
	return u
}

// SetDisconnectedAt sets the "disconnected_at" field.
func (u *StationUpsert) SetDisconnectedAt(v time.Time) *StationUpsert {
	u.Set(station.FieldDisconnectedAt, v)
	return u
}

// UpdateDisconnectedAt sets the "disconnected_at" field to the value that was provided on create.
func (u *StationUpsert) UpdateDisconnectedAt() *StationUpsert {
	u.SetExcluded(station.FieldDisconnectedAt)
	return u
}

// ClearDisconnectedAt clears the value of the "disconnected_at" field.
func (u *StationUpsert) ClearDisconnectedAt() *StationUpsert {
	u.SetNull(station.FieldDisconnectedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Station.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *StationUpsertOne) UpdateNewValues() *StationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.IP(); exists {
			s.SetIgnore(station.FieldIP)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Station.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *StationUpsertOne) Ignore() *StationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StationUpsertOne) DoNothing() *StationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StationCreate.OnConflict
// documentation for more info.
func (u *StationUpsertOne) Update(set func(*StationUpsert)) *StationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StationUpsert{UpdateSet: update})
	}))
	return u
}

// SetConnectedAt sets the "connected_at" field.
func (u *StationUpsertOne) SetConnectedAt(v time.Time) *StationUpsertOne {
	return u.Update(func(s *StationUpsert) {
		s.SetConnectedAt(v)
	})
}

// UpdateConnectedAt sets the "connected_at" field to the value that was provided on create.
func (u *StationUpsertOne) UpdateConnectedAt() *StationUpsertOne {
	return u.Update(func(s *StationUpsert) {
		s.UpdateConnectedAt()
	})
}

// SetDisconnectedAt sets the "disconnected_at" field.
func (u *StationUpsertOne) SetDisconnectedAt(v time.Time) *StationUpsertOne {
	return u.Update(func(s *StationUpsert) {
		s.SetDisconnectedAt(v)
	})
}

// UpdateDisconnectedAt sets the "disconnected_at" field to the value that was provided on create.
func (u *StationUpsertOne) UpdateDisconnectedAt() *StationUpsertOne {
	return u.Update(func(s *StationUpsert) {
		s.UpdateDisconnectedAt()
	})
}

// ClearDisconnectedAt clears the value of the "disconnected_at" field.
func (u *StationUpsertOne) ClearDisconnectedAt() *StationUpsertOne {
	return u.Update(func(s *StationUpsert) {
		s.ClearDisconnectedAt()
	})
}

// Exec executes the query.
func (u *StationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *StationUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *StationUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// StationCreateBulk is the builder for creating many Station entities in bulk.
type StationCreateBulk struct {
	config
	err      error
	builders []*StationCreate
	conflict []sql.ConflictOption
}

// Save creates the Station entities in the database.
func (_c *StationCreateBulk) Save(ctx context.Context) ([]*Station, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Station, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StationCreateBulk) SaveX(ctx context.Context) []*Station {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Station.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StationUpsert) {
//			SetIP(v+v).
//		}).
//		Exec(ctx)
func (_c *StationCreateBulk) OnConflict(opts ...sql.ConflictOption) *StationUpsertBulk {
	_c.conflict = opts
	return &StationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Station.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *StationCreateBulk) OnConflictColumns(columns ...string) *StationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &StationUpsertBulk{
		create: _c,
	}
}

// StationUpsertBulk is the builder for "upsert"-ing
// a bulk of Station nodes.
type StationUpsertBulk struct {
	create *StationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Station.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *StationUpsertBulk) UpdateNewValues() *StationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.IP(); exists {
				s.SetIgnore(station.FieldIP)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Station.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *StationUpsertBulk) Ignore() *StationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StationUpsertBulk) DoNothing() *StationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StationCreateBulk.OnConflict
// documentation for more info.
func (u *StationUpsertBulk) Update(set func(*StationUpsert)) *StationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StationUpsert{UpdateSet: update})
	}))
	return u
}

// SetConnectedAt sets the "connected_at" field.
func (u *StationUpsertBulk) SetConnectedAt(v time.Time) *StationUpsertBulk {
	return u.Update(func(s *StationUpsert) {
		s.SetConnectedAt(v)
	})
}

// UpdateConnectedAt sets the "connected_at" field to the value that was provided on create.
func (u *StationUpsertBulk) UpdateConnectedAt() *StationUpsertBulk {
	return u.Update(func(s *StationUpsert) {
		s.UpdateConnectedAt()
	})
}

// SetDisconnectedAt sets the "disconnected_at" field.
func (u *StationUpsertBulk) SetDisconnectedAt(v time.Time) *StationUpsertBulk {
	return u.Update(func(s *StationUpsert) {
		s.SetDisconnectedAt(v)
	})
}

// UpdateDisconnectedAt sets the "disconnected_at" field to the value that was provided on create.
func (u *StationUpsertBulk) UpdateDisconnectedAt() *StationUpsertBulk {
	return u.Update(func(s *StationUpsert) {
		s.UpdateDisconnectedAt()
	})
}

// ClearDisconnectedAt clears the value of the "disconnected_at" field.
func (u *StationUpsertBulk) ClearDisconnectedAt() *StationUpsertBulk {
	return u.Update(func(s *StationUpsert) {
		s.ClearDisconnectedAt()
	})
}

// Exec executes the query.
func (u *StationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the StationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
