// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/contestareamap"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/station"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/tableelement"
	"github.com/google/uuid"
)

// TableElement is the model entity for the TableElement schema.
type TableElement struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// X holds the value of the "x" field.
	X int `json:"x,omitempty"`
	// Y holds the value of the "y" field.
	Y int `json:"y,omitempty"`
	// Rotation holds the value of the "rotation" field.
	Rotation tableelement.Rotation `json:"rotation,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TableElementQuery when eager-loading is set.
	Edges                   TableElementEdges `json:"edges"`
	contest_area_map_tables *int
	table_element_station   *int
	selectValues            sql.SelectValues
}

// TableElementEdges holds the relations/edges for other nodes in the graph.
type TableElementEdges struct {
	// Map holds the value of the map edge.
	Map *ContestAreaMap `json:"map,omitempty"`
	// Station holds the value of the station edge.
	Station *Station `json:"station,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MapOrErr returns the Map value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TableElementEdges) MapOrErr() (*ContestAreaMap, error) {
	if e.Map != nil {
		return e.Map, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: contestareamap.Label}
	}
	return nil, &NotLoadedError{edge: "map"}
}

// StationOrErr returns the Station value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TableElementEdges) StationOrErr() (*Station, error) {
	if e.Station != nil {
		return e.Station, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: station.Label}
	}
	return nil, &NotLoadedError{edge: "station"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TableElement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tableelement.FieldX, tableelement.FieldY:
			values[i] = new(sql.NullInt64)
		case tableelement.FieldRotation:
			values[i] = new(sql.NullString)
		case tableelement.FieldID:
			values[i] = new(uuid.UUID)
		case tableelement.ForeignKeys[0]: // contest_area_map_tables
			values[i] = new(sql.NullInt64)
		case tableelement.ForeignKeys[1]: // table_element_station
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TableElement fields.
func (_m *TableElement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tableelement.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case tableelement.FieldX:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field x", values[i])
			} else if value.Valid {
				_m.X = int(value.Int64)
			}
		case tableelement.FieldY:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field y", values[i])
			} else if value.Valid {
				_m.Y = int(value.Int64)
			}
		case tableelement.FieldRotation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rotation", values[i])
			} else if value.Valid {
				_m.Rotation = tableelement.Rotation(value.String)
			}
		case tableelement.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field contest_area_map_tables", value)
			} else if value.Valid {
				_m.contest_area_map_tables = new(int)
				*_m.contest_area_map_tables = int(value.Int64)
			}
		case tableelement.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field table_element_station", value)
			} else if value.Valid {
				_m.table_element_station = new(int)
				*_m.table_element_station = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TableElement.
// This includes values selected through modifiers, order, etc.
func (_m *TableElement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMap queries the "map" edge of the TableElement entity.
func (_m *TableElement) QueryMap() *ContestAreaMapQuery {
	return NewTableElementClient(_m.config).QueryMap(_m)
}

// QueryStation queries the "station" edge of the TableElement entity.
func (_m *TableElement) QueryStation() *StationQuery {
	return NewTableElementClient(_m.config).QueryStation(_m)
}

// Update returns a builder for updating this TableElement.
// Note that you need to call TableElement.Unwrap() before calling this method if this TableElement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TableElement) Update() *TableElementUpdateOne {
	return NewTableElementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TableElement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TableElement) Unwrap() *TableElement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TableElement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TableElement) String() string {
	var builder strings.Builder
	builder.WriteString("TableElement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("x=")
	builder.WriteString(fmt.Sprintf("%v", _m.X))
	builder.WriteString(", ")
	builder.WriteString("y=")
	builder.WriteString(fmt.Sprintf("%v", _m.Y))
	builder.WriteString(", ")
	builder.WriteString("rotation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rotation))
	builder.WriteByte(')')
	return builder.String()
}

// TableElements is a parsable slice of TableElement.
type TableElements []*TableElement
