// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/contest"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/predicate"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/station"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/team"
)

// TeamUpdate is the builder for updating Team entities.
type TeamUpdate struct {
	config
	hooks    []Hook
	mutation *TeamMutation
}

// Where appends a list predicates to the TeamUpdate builder.
func (_u *TeamUpdate) Where(ps ...predicate.Team) *TeamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TeamUpdate) SetName(v string) *TeamUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableName(v *string) *TeamUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStationID sets the "station" edge to the Station entity by ID.
func (_u *TeamUpdate) SetStationID(id int) *TeamUpdate {
	_u.mutation.SetStationID(id)
	return _u
}

// SetNillableStationID sets the "station" edge to the Station entity by ID if the given value is not nil.
func (_u *TeamUpdate) SetNillableStationID(id *int) *TeamUpdate {
	if id != nil {
		_u = _u.SetStationID(*id)
	}
	return _u
}

// SetStation sets the "station" edge to the Station entity.
func (_u *TeamUpdate) SetStation(v *Station) *TeamUpdate {
	return _u.SetStationID(v.ID)
}

// AddContestIDs adds the "contests" edge to the Contest entity by IDs.
func (_u *TeamUpdate) AddContestIDs(ids ...string) *TeamUpdate {
	_u.mutation.AddContestIDs(ids...)
	return _u
}

// AddContests adds the "contests" edges to the Contest entity.
func (_u *TeamUpdate) AddContests(v ...*Contest) *TeamUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContestIDs(ids...)
}

// Mutation returns the TeamMutation object of the builder.
func (_u *TeamUpdate) Mutation() *TeamMutation {
	return _u.mutation
}

// ClearStation clears the "station" edge to the Station entity.
func (_u *TeamUpdate) ClearStation() *TeamUpdate {
	_u.mutation.ClearStation()
	return _u
}

// ClearContests clears all "contests" edges to the Contest entity.
func (_u *TeamUpdate) ClearContests() *TeamUpdate {
	_u.mutation.ClearContests()
	return _u
}

// RemoveContestIDs removes the "contests" edge to Contest entities by IDs.
func (_u *TeamUpdate) RemoveContestIDs(ids ...string) *TeamUpdate {
	_u.mutation.RemoveContestIDs(ids...)
	return _u
}

// RemoveContests removes "contests" edges to Contest entities.
func (_u *TeamUpdate) RemoveContests(v ...*Contest) *TeamUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContestIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TeamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(team.Table, team.Columns, sqlgraph.NewFieldSpec(team.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(team.FieldName, field.TypeString, value)
	}
	if _u.mutation.StationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   team.StationTable,
			Columns: []string{team.StationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(station.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   team.StationTable,
			Columns: []string{team.StationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(station.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   team.ContestsTable,
			Columns: team.ContestsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContestsIDs(); len(nodes) > 0 && !_u.mutation.ContestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   team.ContestsTable,
			Columns: team.ContestsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   team.ContestsTable,
			Columns: team.ContestsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{team.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamUpdateOne is the builder for updating a single Team entity.
type TeamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamMutation
}

// SetName sets the "name" field.
func (_u *TeamUpdateOne) SetName(v string) *TeamUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableName(v *string) *TeamUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStationID sets the "station" edge to the Station entity by ID.
func (_u *TeamUpdateOne) SetStationID(id int) *TeamUpdateOne {
	_u.mutation.SetStationID(id)
	return _u
}

// SetNillableStationID sets the "station" edge to the Station entity by ID if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableStationID(id *int) *TeamUpdateOne {
	if id != nil {
		_u = _u.SetStationID(*id)
	}
	return _u
}

// SetStation sets the "station" edge to the Station entity.
func (_u *TeamUpdateOne) SetStation(v *Station) *TeamUpdateOne {
	return _u.SetStationID(v.ID)
}

// AddContestIDs adds the "contests" edge to the Contest entity by IDs.
func (_u *TeamUpdateOne) AddContestIDs(ids ...string) *TeamUpdateOne {
	_u.mutation.AddContestIDs(ids...)
	return _u
}

// AddContests adds the "contests" edges to the Contest entity.
func (_u *TeamUpdateOne) AddContests(v ...*Contest) *TeamUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContestIDs(ids...)
}

// Mutation returns the TeamMutation object of the builder.
func (_u *TeamUpdateOne) Mutation() *TeamMutation {
	return _u.mutation
}

// ClearStation clears the "station" edge to the Station entity.
func (_u *TeamUpdateOne) ClearStation() *TeamUpdateOne {
	_u.mutation.ClearStation()
	return _u
}

// ClearContests clears all "contests" edges to the Contest entity.
func (_u *TeamUpdateOne) ClearContests() *TeamUpdateOne {
	_u.mutation.ClearContests()
	return _u
}

// RemoveContestIDs removes the "contests" edge to Contest entities by IDs.
func (_u *TeamUpdateOne) RemoveContestIDs(ids ...string) *TeamUpdateOne {
	_u.mutation.RemoveContestIDs(ids...)
	return _u
}

// RemoveContests removes "contests" edges to Contest entities.
func (_u *TeamUpdateOne) RemoveContests(v ...*Contest) *TeamUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContestIDs(ids...)
}

// Where appends a list predicates to the TeamUpdate builder.
func (_u *TeamUpdateOne) Where(ps ...predicate.Team) *TeamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamUpdateOne) Select(field string, fields ...string) *TeamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Team entity.
func (_u *TeamUpdateOne) Save(ctx context.Context) (*Team, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUpdateOne) SaveX(ctx context.Context) *Team {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TeamUpdateOne) sqlSave(ctx context.Context) (_node *Team, err error) {
	_spec := sqlgraph.NewUpdateSpec(team.Table, team.Columns, sqlgraph.NewFieldSpec(team.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Team.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, team.FieldID)
		for _, f := range fields {
			if !team.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != team.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(team.FieldName, field.TypeString, value)
	}
	if _u.mutation.StationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   team.StationTable,
			Columns: []string{team.StationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(station.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   team.StationTable,
			Columns: []string{team.StationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(station.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   team.ContestsTable,
			Columns: team.ContestsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContestsIDs(); len(nodes) > 0 && !_u.mutation.ContestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   team.ContestsTable,
			Columns: team.ContestsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   team.ContestsTable,
			Columns: team.ContestsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contest.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Team{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{team.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
