// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/contestareamap"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/wallelement"
	"github.com/google/uuid"
)

// WallElement is the model entity for the WallElement schema.
type WallElement struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// XStart holds the value of the "x_start" field.
	XStart int `json:"x_start,omitempty"`
	// YStart holds the value of the "y_start" field.
	YStart int `json:"y_start,omitempty"`
	// XEnd holds the value of the "x_end" field.
	XEnd int `json:"x_end,omitempty"`
	// YEnd holds the value of the "y_end" field.
	YEnd int `json:"y_end,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WallElementQuery when eager-loading is set.
	Edges                  WallElementEdges `json:"edges"`
	contest_area_map_walls *int
	selectValues           sql.SelectValues
}

// WallElementEdges holds the relations/edges for other nodes in the graph.
type WallElementEdges struct {
	// Map holds the value of the map edge.
	Map *ContestAreaMap `json:"map,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MapOrErr returns the Map value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WallElementEdges) MapOrErr() (*ContestAreaMap, error) {
	if e.Map != nil {
		return e.Map, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: contestareamap.Label}
	}
	return nil, &NotLoadedError{edge: "map"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WallElement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wallelement.FieldXStart, wallelement.FieldYStart, wallelement.FieldXEnd, wallelement.FieldYEnd:
			values[i] = new(sql.NullInt64)
		case wallelement.FieldID:
			values[i] = new(uuid.UUID)
		case wallelement.ForeignKeys[0]: // contest_area_map_walls
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WallElement fields.
func (_m *WallElement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wallelement.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case wallelement.FieldXStart:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field x_start", values[i])
			} else if value.Valid {
				_m.XStart = int(value.Int64)
			}
		case wallelement.FieldYStart:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field y_start", values[i])
			} else if value.Valid {
				_m.YStart = int(value.Int64)
			}
		case wallelement.FieldXEnd:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field x_end", values[i])
			} else if value.Valid {
				_m.XEnd = int(value.Int64)
			}
		case wallelement.FieldYEnd:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field y_end", values[i])
			} else if value.Valid {
				_m.YEnd = int(value.Int64)
			}
		case wallelement.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field contest_area_map_walls", value)
			} else if value.Valid {
				_m.contest_area_map_walls = new(int)
				*_m.contest_area_map_walls = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WallElement.
// This includes values selected through modifiers, order, etc.
func (_m *WallElement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMap queries the "map" edge of the WallElement entity.
func (_m *WallElement) QueryMap() *ContestAreaMapQuery {
	return NewWallElementClient(_m.config).QueryMap(_m)
}

// Update returns a builder for updating this WallElement.
// Note that you need to call WallElement.Unwrap() before calling this method if this WallElement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WallElement) Update() *WallElementUpdateOne {
	return NewWallElementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WallElement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WallElement) Unwrap() *WallElement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WallElement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WallElement) String() string {
	var builder strings.Builder
	builder.WriteString("WallElement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("x_start=")
	builder.WriteString(fmt.Sprintf("%v", _m.XStart))
	builder.WriteString(", ")
	builder.WriteString("y_start=")
	builder.WriteString(fmt.Sprintf("%v", _m.YStart))
	builder.WriteString(", ")
	builder.WriteString("x_end=")
	builder.WriteString(fmt.Sprintf("%v", _m.XEnd))
	builder.WriteString(", ")
	builder.WriteString("y_end=")
	builder.WriteString(fmt.Sprintf("%v", _m.YEnd))
	builder.WriteByte(')')
	return builder.String()
}

// WallElements is a parsable slice of WallElement.
type WallElements []*WallElement
