// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/wallpaper"
)

// WallpaperCreate is the builder for creating a Wallpaper entity.
type WallpaperCreate struct {
	config
	mutation *WallpaperMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetImageData sets the "image_data" field.
func (_c *WallpaperCreate) SetImageData(v []byte) *WallpaperCreate {
	_c.mutation.SetImageData(v)
	return _c
}

// SetContestID sets the "contest_id" field.
func (_c *WallpaperCreate) SetContestID(v string) *WallpaperCreate {
	_c.mutation.SetContestID(v)
	return _c
}

// Mutation returns the WallpaperMutation object of the builder.
func (_c *WallpaperCreate) Mutation() *WallpaperMutation {
	return _c.mutation
}

// Save creates the Wallpaper in the database.
func (_c *WallpaperCreate) Save(ctx context.Context) (*Wallpaper, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WallpaperCreate) SaveX(ctx context.Context) *Wallpaper {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WallpaperCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WallpaperCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WallpaperCreate) check() error {
	if _, ok := _c.mutation.ImageData(); !ok {
		return &ValidationError{Name: "image_data", err: errors.New(`ent: missing required field "Wallpaper.image_data"`)}
	}
	if _, ok := _c.mutation.ContestID(); !ok {
		return &ValidationError{Name: "contest_id", err: errors.New(`ent: missing required field "Wallpaper.contest_id"`)}
	}
	return nil
}

func (_c *WallpaperCreate) sqlSave(ctx context.Context) (*Wallpaper, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WallpaperCreate) createSpec() (*Wallpaper, *sqlgraph.CreateSpec) {
	var (
		_node = &Wallpaper{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wallpaper.Table, sqlgraph.NewFieldSpec(wallpaper.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ImageData(); ok {
		_spec.SetField(wallpaper.FieldImageData, field.TypeBytes, value)
		_node.ImageData = value
	}
	if value, ok := _c.mutation.ContestID(); ok {
		_spec.SetField(wallpaper.FieldContestID, field.TypeString, value)
		_node.ContestID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Wallpaper.Create().
//		SetImageData(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WallpaperUpsert) {
//			SetImageData(v+v).
//		}).
//		Exec(ctx)
func (_c *WallpaperCreate) OnConflict(opts ...sql.ConflictOption) *WallpaperUpsertOne {
	_c.conflict = opts
	return &WallpaperUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Wallpaper.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WallpaperCreate) OnConflictColumns(columns ...string) *WallpaperUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WallpaperUpsertOne{
		create: _c,
	}
}

type (
	// WallpaperUpsertOne is the builder for "upsert"-ing
	//  one Wallpaper node.
	WallpaperUpsertOne struct {
		create *WallpaperCreate
	}

	// WallpaperUpsert is the "OnConflict" setter.
	WallpaperUpsert struct {
		*sql.UpdateSet
	}
)

// SetImageData sets the "image_data" field.
func (u *WallpaperUpsert) SetImageData(v []byte) *WallpaperUpsert {
	u.Set(wallpaper.FieldImageData, v)
	return u
}

// UpdateImageData sets the "image_data" field to the value that was provided on create.
func (u *WallpaperUpsert) UpdateImageData() *WallpaperUpsert {
	u.SetExcluded(wallpaper.FieldImageData)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Wallpaper.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WallpaperUpsertOne) UpdateNewValues() *WallpaperUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ContestID(); exists {
			s.SetIgnore(wallpaper.FieldContestID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Wallpaper.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WallpaperUpsertOne) Ignore() *WallpaperUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WallpaperUpsertOne) DoNothing() *WallpaperUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WallpaperCreate.OnConflict
// documentation for more info.
func (u *WallpaperUpsertOne) Update(set func(*WallpaperUpsert)) *WallpaperUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WallpaperUpsert{UpdateSet: update})
	}))
	return u
}

// SetImageData sets the "image_data" field.
func (u *WallpaperUpsertOne) SetImageData(v []byte) *WallpaperUpsertOne {
	return u.Update(func(s *WallpaperUpsert) {
		s.SetImageData(v)
	})
}

// UpdateImageData sets the "image_data" field to the value that was provided on create.
func (u *WallpaperUpsertOne) UpdateImageData() *WallpaperUpsertOne {
	return u.Update(func(s *WallpaperUpsert) {
		s.UpdateImageData()
	})
}

// Exec executes the query.
func (u *WallpaperUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WallpaperCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WallpaperUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WallpaperUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WallpaperUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WallpaperCreateBulk is the builder for creating many Wallpaper entities in bulk.
type WallpaperCreateBulk struct {
	config
	err      error
	builders []*WallpaperCreate
	conflict []sql.ConflictOption
}

// Save creates the Wallpaper entities in the database.
func (_c *WallpaperCreateBulk) Save(ctx context.Context) ([]*Wallpaper, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Wallpaper, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WallpaperMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WallpaperCreateBulk) SaveX(ctx context.Context) []*Wallpaper {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WallpaperCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WallpaperCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Wallpaper.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WallpaperUpsert) {
//			SetImageData(v+v).
//		}).
//		Exec(ctx)
func (_c *WallpaperCreateBulk) OnConflict(opts ...sql.ConflictOption) *WallpaperUpsertBulk {
	_c.conflict = opts
	return &WallpaperUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Wallpaper.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WallpaperCreateBulk) OnConflictColumns(columns ...string) *WallpaperUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WallpaperUpsertBulk{
		create: _c,
	}
}

// WallpaperUpsertBulk is the builder for "upsert"-ing
// a bulk of Wallpaper nodes.
type WallpaperUpsertBulk struct {
	create *WallpaperCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Wallpaper.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WallpaperUpsertBulk) UpdateNewValues() *WallpaperUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ContestID(); exists {
				s.SetIgnore(wallpaper.FieldContestID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Wallpaper.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WallpaperUpsertBulk) Ignore() *WallpaperUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WallpaperUpsertBulk) DoNothing() *WallpaperUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WallpaperCreateBulk.OnConflict
// documentation for more info.
func (u *WallpaperUpsertBulk) Update(set func(*WallpaperUpsert)) *WallpaperUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WallpaperUpsert{UpdateSet: update})
	}))
	return u
}

// SetImageData sets the "image_data" field.
func (u *WallpaperUpsertBulk) SetImageData(v []byte) *WallpaperUpsertBulk {
	return u.Update(func(s *WallpaperUpsert) {
		s.SetImageData(v)
	})
}

// UpdateImageData sets the "image_data" field to the value that was provided on create.
func (u *WallpaperUpsertBulk) UpdateImageData() *WallpaperUpsertBulk {
	return u.Update(func(s *WallpaperUpsert) {
		s.UpdateImageData()
	})
}

// Exec executes the query.
func (u *WallpaperUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WallpaperCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WallpaperCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WallpaperUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
