// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/contestareamap"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/predicate"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/wallelement"
)

// WallElementUpdate is the builder for updating WallElement entities.
type WallElementUpdate struct {
	config
	hooks    []Hook
	mutation *WallElementMutation
}

// Where appends a list predicates to the WallElementUpdate builder.
func (_u *WallElementUpdate) Where(ps ...predicate.WallElement) *WallElementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetXStart sets the "x_start" field.
func (_u *WallElementUpdate) SetXStart(v int) *WallElementUpdate {
	_u.mutation.ResetXStart()
	_u.mutation.SetXStart(v)
	return _u
}

// SetNillableXStart sets the "x_start" field if the given value is not nil.
func (_u *WallElementUpdate) SetNillableXStart(v *int) *WallElementUpdate {
	if v != nil {
		_u.SetXStart(*v)
	}
	return _u
}

// AddXStart adds value to the "x_start" field.
func (_u *WallElementUpdate) AddXStart(v int) *WallElementUpdate {
	_u.mutation.AddXStart(v)
	return _u
}

// SetYStart sets the "y_start" field.
func (_u *WallElementUpdate) SetYStart(v int) *WallElementUpdate {
	_u.mutation.ResetYStart()
	_u.mutation.SetYStart(v)
	return _u
}

// SetNillableYStart sets the "y_start" field if the given value is not nil.
func (_u *WallElementUpdate) SetNillableYStart(v *int) *WallElementUpdate {
	if v != nil {
		_u.SetYStart(*v)
	}
	return _u
}

// AddYStart adds value to the "y_start" field.
func (_u *WallElementUpdate) AddYStart(v int) *WallElementUpdate {
	_u.mutation.AddYStart(v)
	return _u
}

// SetXEnd sets the "x_end" field.
func (_u *WallElementUpdate) SetXEnd(v int) *WallElementUpdate {
	_u.mutation.ResetXEnd()
	_u.mutation.SetXEnd(v)
	return _u
}

// SetNillableXEnd sets the "x_end" field if the given value is not nil.
func (_u *WallElementUpdate) SetNillableXEnd(v *int) *WallElementUpdate {
	if v != nil {
		_u.SetXEnd(*v)
	}
	return _u
}

// AddXEnd adds value to the "x_end" field.
func (_u *WallElementUpdate) AddXEnd(v int) *WallElementUpdate {
	_u.mutation.AddXEnd(v)
	return _u
}

// SetYEnd sets the "y_end" field.
func (_u *WallElementUpdate) SetYEnd(v int) *WallElementUpdate {
	_u.mutation.ResetYEnd()
	_u.mutation.SetYEnd(v)
	return _u
}

// SetNillableYEnd sets the "y_end" field if the given value is not nil.
func (_u *WallElementUpdate) SetNillableYEnd(v *int) *WallElementUpdate {
	if v != nil {
		_u.SetYEnd(*v)
	}
	return _u
}

// AddYEnd adds value to the "y_end" field.
func (_u *WallElementUpdate) AddYEnd(v int) *WallElementUpdate {
	_u.mutation.AddYEnd(v)
	return _u
}

// SetMapID sets the "map" edge to the ContestAreaMap entity by ID.
func (_u *WallElementUpdate) SetMapID(id int) *WallElementUpdate {
	_u.mutation.SetMapID(id)
	return _u
}

// SetNillableMapID sets the "map" edge to the ContestAreaMap entity by ID if the given value is not nil.
func (_u *WallElementUpdate) SetNillableMapID(id *int) *WallElementUpdate {
	if id != nil {
		_u = _u.SetMapID(*id)
	}
	return _u
}

// SetMap sets the "map" edge to the ContestAreaMap entity.
func (_u *WallElementUpdate) SetMap(v *ContestAreaMap) *WallElementUpdate {
	return _u.SetMapID(v.ID)
}

// Mutation returns the WallElementMutation object of the builder.
func (_u *WallElementUpdate) Mutation() *WallElementMutation {
	return _u.mutation
}

// ClearMap clears the "map" edge to the ContestAreaMap entity.
func (_u *WallElementUpdate) ClearMap() *WallElementUpdate {
	_u.mutation.ClearMap()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WallElementUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WallElementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WallElementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WallElementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WallElementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(wallelement.Table, wallelement.Columns, sqlgraph.NewFieldSpec(wallelement.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.XStart(); ok {
		_spec.SetField(wallelement.FieldXStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedXStart(); ok {
		_spec.AddField(wallelement.FieldXStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.YStart(); ok {
		_spec.SetField(wallelement.FieldYStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYStart(); ok {
		_spec.AddField(wallelement.FieldYStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.XEnd(); ok {
		_spec.SetField(wallelement.FieldXEnd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedXEnd(); ok {
		_spec.AddField(wallelement.FieldXEnd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.YEnd(); ok {
		_spec.SetField(wallelement.FieldYEnd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYEnd(); ok {
		_spec.AddField(wallelement.FieldYEnd, field.TypeInt, value)
	}
	if _u.mutation.MapCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wallelement.MapTable,
			Columns: []string{wallelement.MapColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contestareamap.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MapIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wallelement.MapTable,
			Columns: []string{wallelement.MapColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contestareamap.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallelement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WallElementUpdateOne is the builder for updating a single WallElement entity.
type WallElementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WallElementMutation
}

// SetXStart sets the "x_start" field.
func (_u *WallElementUpdateOne) SetXStart(v int) *WallElementUpdateOne {
	_u.mutation.ResetXStart()
	_u.mutation.SetXStart(v)
	return _u
}

// SetNillableXStart sets the "x_start" field if the given value is not nil.
func (_u *WallElementUpdateOne) SetNillableXStart(v *int) *WallElementUpdateOne {
	if v != nil {
		_u.SetXStart(*v)
	}
	return _u
}

// AddXStart adds value to the "x_start" field.
func (_u *WallElementUpdateOne) AddXStart(v int) *WallElementUpdateOne {
	_u.mutation.AddXStart(v)
	return _u
}

// SetYStart sets the "y_start" field.
func (_u *WallElementUpdateOne) SetYStart(v int) *WallElementUpdateOne {
	_u.mutation.ResetYStart()
	_u.mutation.SetYStart(v)
	return _u
}

// SetNillableYStart sets the "y_start" field if the given value is not nil.
func (_u *WallElementUpdateOne) SetNillableYStart(v *int) *WallElementUpdateOne {
	if v != nil {
		_u.SetYStart(*v)
	}
	return _u
}

// AddYStart adds value to the "y_start" field.
func (_u *WallElementUpdateOne) AddYStart(v int) *WallElementUpdateOne {
	_u.mutation.AddYStart(v)
	return _u
}

// SetXEnd sets the "x_end" field.
func (_u *WallElementUpdateOne) SetXEnd(v int) *WallElementUpdateOne {
	_u.mutation.ResetXEnd()
	_u.mutation.SetXEnd(v)
	return _u
}

// SetNillableXEnd sets the "x_end" field if the given value is not nil.
func (_u *WallElementUpdateOne) SetNillableXEnd(v *int) *WallElementUpdateOne {
	if v != nil {
		_u.SetXEnd(*v)
	}
	return _u
}

// AddXEnd adds value to the "x_end" field.
func (_u *WallElementUpdateOne) AddXEnd(v int) *WallElementUpdateOne {
	_u.mutation.AddXEnd(v)
	return _u
}

// SetYEnd sets the "y_end" field.
func (_u *WallElementUpdateOne) SetYEnd(v int) *WallElementUpdateOne {
	_u.mutation.ResetYEnd()
	_u.mutation.SetYEnd(v)
	return _u
}

// SetNillableYEnd sets the "y_end" field if the given value is not nil.
func (_u *WallElementUpdateOne) SetNillableYEnd(v *int) *WallElementUpdateOne {
	if v != nil {
		_u.SetYEnd(*v)
	}
	return _u
}

// AddYEnd adds value to the "y_end" field.
func (_u *WallElementUpdateOne) AddYEnd(v int) *WallElementUpdateOne {
	_u.mutation.AddYEnd(v)
	return _u
}

// SetMapID sets the "map" edge to the ContestAreaMap entity by ID.
func (_u *WallElementUpdateOne) SetMapID(id int) *WallElementUpdateOne {
	_u.mutation.SetMapID(id)
	return _u
}

// SetNillableMapID sets the "map" edge to the ContestAreaMap entity by ID if the given value is not nil.
func (_u *WallElementUpdateOne) SetNillableMapID(id *int) *WallElementUpdateOne {
	if id != nil {
		_u = _u.SetMapID(*id)
	}
	return _u
}

// SetMap sets the "map" edge to the ContestAreaMap entity.
func (_u *WallElementUpdateOne) SetMap(v *ContestAreaMap) *WallElementUpdateOne {
	return _u.SetMapID(v.ID)
}

// Mutation returns the WallElementMutation object of the builder.
func (_u *WallElementUpdateOne) Mutation() *WallElementMutation {
	return _u.mutation
}

// ClearMap clears the "map" edge to the ContestAreaMap entity.
func (_u *WallElementUpdateOne) ClearMap() *WallElementUpdateOne {
	_u.mutation.ClearMap()
	return _u
}

// Where appends a list predicates to the WallElementUpdate builder.
func (_u *WallElementUpdateOne) Where(ps ...predicate.WallElement) *WallElementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WallElementUpdateOne) Select(field string, fields ...string) *WallElementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WallElement entity.
func (_u *WallElementUpdateOne) Save(ctx context.Context) (*WallElement, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WallElementUpdateOne) SaveX(ctx context.Context) *WallElement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WallElementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WallElementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WallElementUpdateOne) sqlSave(ctx context.Context) (_node *WallElement, err error) {
	_spec := sqlgraph.NewUpdateSpec(wallelement.Table, wallelement.Columns, sqlgraph.NewFieldSpec(wallelement.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WallElement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wallelement.FieldID)
		for _, f := range fields {
			if !wallelement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wallelement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.XStart(); ok {
		_spec.SetField(wallelement.FieldXStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedXStart(); ok {
		_spec.AddField(wallelement.FieldXStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.YStart(); ok {
		_spec.SetField(wallelement.FieldYStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYStart(); ok {
		_spec.AddField(wallelement.FieldYStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.XEnd(); ok {
		_spec.SetField(wallelement.FieldXEnd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedXEnd(); ok {
		_spec.AddField(wallelement.FieldXEnd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.YEnd(); ok {
		_spec.SetField(wallelement.FieldYEnd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYEnd(); ok {
		_spec.AddField(wallelement.FieldYEnd, field.TypeInt, value)
	}
	if _u.mutation.MapCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wallelement.MapTable,
			Columns: []string{wallelement.MapColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contestareamap.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MapIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wallelement.MapTable,
			Columns: []string{wallelement.MapColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contestareamap.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WallElement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallelement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
