// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/wallpaper"
)

// Wallpaper is the model entity for the Wallpaper schema.
type Wallpaper struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ImageData holds the value of the "image_data" field.
	ImageData *[]byte `json:"image_data,omitempty"`
	// ContestID holds the value of the "contest_id" field.
	ContestID    string `json:"contest_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Wallpaper) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wallpaper.FieldImageData:
			values[i] = new([]byte)
		case wallpaper.FieldID:
			values[i] = new(sql.NullInt64)
		case wallpaper.FieldContestID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Wallpaper fields.
func (_m *Wallpaper) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wallpaper.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case wallpaper.FieldImageData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field image_data", values[i])
			} else if value != nil {
				_m.ImageData = value
			}
		case wallpaper.FieldContestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contest_id", values[i])
			} else if value.Valid {
				_m.ContestID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Wallpaper.
// This includes values selected through modifiers, order, etc.
func (_m *Wallpaper) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Wallpaper.
// Note that you need to call Wallpaper.Unwrap() before calling this method if this Wallpaper
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Wallpaper) Update() *WallpaperUpdateOne {
	return NewWallpaperClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Wallpaper entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Wallpaper) Unwrap() *Wallpaper {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Wallpaper is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Wallpaper) String() string {
	var builder strings.Builder
	builder.WriteString("Wallpaper(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.ImageData; v != nil {
		builder.WriteString("image_data=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("contest_id=")
	builder.WriteString(_m.ContestID)
	builder.WriteByte(')')
	return builder.String()
}

// Wallpapers is a parsable slice of Wallpaper.
type Wallpapers []*Wallpaper
