// Code generated by ent, DO NOT EDIT.

package wallelement

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the wallelement type in the database.
	Label = "wall_element"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldXStart holds the string denoting the x_start field in the database.
	FieldXStart = "x_start"
	// FieldYStart holds the string denoting the y_start field in the database.
	FieldYStart = "y_start"
	// FieldXEnd holds the string denoting the x_end field in the database.
	FieldXEnd = "x_end"
	// FieldYEnd holds the string denoting the y_end field in the database.
	FieldYEnd = "y_end"
	// EdgeMap holds the string denoting the map edge name in mutations.
	EdgeMap = "map"
	// Table holds the table name of the wallelement in the database.
	Table = "wall_elements"
	// MapTable is the table that holds the map relation/edge.
	MapTable = "wall_elements"
	// MapInverseTable is the table name for the ContestAreaMap entity.
	// It exists in this package in order to avoid circular dependency with the "contestareamap" package.
	MapInverseTable = "contest_area_maps"
	// MapColumn is the table column denoting the map relation/edge.
	MapColumn = "contest_area_map_walls"
)

// Columns holds all SQL columns for wallelement fields.
var Columns = []string{
	FieldID,
	FieldXStart,
	FieldYStart,
	FieldXEnd,
	FieldYEnd,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "wall_elements"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"contest_area_map_walls",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the WallElement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByXStart orders the results by the x_start field.
func ByXStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldXStart, opts...).ToFunc()
}

// ByYStart orders the results by the y_start field.
func ByYStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYStart, opts...).ToFunc()
}

// ByXEnd orders the results by the x_end field.
func ByXEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldXEnd, opts...).ToFunc()
}

// ByYEnd orders the results by the y_end field.
func ByYEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYEnd, opts...).ToFunc()
}

// ByMapField orders the results by map field.
func ByMapField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMapStep(), sql.OrderByField(field, opts...))
	}
}
func newMapStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MapInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MapTable, MapColumn),
	)
}
