// Code generated by ent, DO NOT EDIT.

package wallelement

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.WallElement {
	return predicate.WallElement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.WallElement {
	return predicate.WallElement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.WallElement {
	return predicate.WallElement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.WallElement {
	return predicate.WallElement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.WallElement {
	return predicate.WallElement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.WallElement {
	return predicate.WallElement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.WallElement {
	return predicate.WallElement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.WallElement {
	return predicate.WallElement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.WallElement {
	return predicate.WallElement(sql.FieldLTE(FieldID, id))
}

// XStart applies equality check predicate on the "x_start" field. It's identical to XStartEQ.
func XStart(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldEQ(FieldXStart, v))
}

// YStart applies equality check predicate on the "y_start" field. It's identical to YStartEQ.
func YStart(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldEQ(FieldYStart, v))
}

// XEnd applies equality check predicate on the "x_end" field. It's identical to XEndEQ.
func XEnd(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldEQ(FieldXEnd, v))
}

// YEnd applies equality check predicate on the "y_end" field. It's identical to YEndEQ.
func YEnd(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldEQ(FieldYEnd, v))
}

// XStartEQ applies the EQ predicate on the "x_start" field.
func XStartEQ(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldEQ(FieldXStart, v))
}

// XStartNEQ applies the NEQ predicate on the "x_start" field.
func XStartNEQ(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldNEQ(FieldXStart, v))
}

// XStartIn applies the In predicate on the "x_start" field.
func XStartIn(vs ...int) predicate.WallElement {
	return predicate.WallElement(sql.FieldIn(FieldXStart, vs...))
}

// XStartNotIn applies the NotIn predicate on the "x_start" field.
func XStartNotIn(vs ...int) predicate.WallElement {
	return predicate.WallElement(sql.FieldNotIn(FieldXStart, vs...))
}

// XStartGT applies the GT predicate on the "x_start" field.
func XStartGT(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldGT(FieldXStart, v))
}

// XStartGTE applies the GTE predicate on the "x_start" field.
func XStartGTE(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldGTE(FieldXStart, v))
}

// XStartLT applies the LT predicate on the "x_start" field.
func XStartLT(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldLT(FieldXStart, v))
}

// XStartLTE applies the LTE predicate on the "x_start" field.
func XStartLTE(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldLTE(FieldXStart, v))
}

// YStartEQ applies the EQ predicate on the "y_start" field.
func YStartEQ(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldEQ(FieldYStart, v))
}

// YStartNEQ applies the NEQ predicate on the "y_start" field.
func YStartNEQ(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldNEQ(FieldYStart, v))
}

// YStartIn applies the In predicate on the "y_start" field.
func YStartIn(vs ...int) predicate.WallElement {
	return predicate.WallElement(sql.FieldIn(FieldYStart, vs...))
}

// YStartNotIn applies the NotIn predicate on the "y_start" field.
func YStartNotIn(vs ...int) predicate.WallElement {
	return predicate.WallElement(sql.FieldNotIn(FieldYStart, vs...))
}

// YStartGT applies the GT predicate on the "y_start" field.
func YStartGT(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldGT(FieldYStart, v))
}

// YStartGTE applies the GTE predicate on the "y_start" field.
func YStartGTE(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldGTE(FieldYStart, v))
}

// YStartLT applies the LT predicate on the "y_start" field.
func YStartLT(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldLT(FieldYStart, v))
}

// YStartLTE applies the LTE predicate on the "y_start" field.
func YStartLTE(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldLTE(FieldYStart, v))
}

// XEndEQ applies the EQ predicate on the "x_end" field.
func XEndEQ(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldEQ(FieldXEnd, v))
}

// XEndNEQ applies the NEQ predicate on the "x_end" field.
func XEndNEQ(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldNEQ(FieldXEnd, v))
}

// XEndIn applies the In predicate on the "x_end" field.
func XEndIn(vs ...int) predicate.WallElement {
	return predicate.WallElement(sql.FieldIn(FieldXEnd, vs...))
}

// XEndNotIn applies the NotIn predicate on the "x_end" field.
func XEndNotIn(vs ...int) predicate.WallElement {
	return predicate.WallElement(sql.FieldNotIn(FieldXEnd, vs...))
}

// XEndGT applies the GT predicate on the "x_end" field.
func XEndGT(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldGT(FieldXEnd, v))
}

// XEndGTE applies the GTE predicate on the "x_end" field.
func XEndGTE(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldGTE(FieldXEnd, v))
}

// XEndLT applies the LT predicate on the "x_end" field.
func XEndLT(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldLT(FieldXEnd, v))
}

// XEndLTE applies the LTE predicate on the "x_end" field.
func XEndLTE(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldLTE(FieldXEnd, v))
}

// YEndEQ applies the EQ predicate on the "y_end" field.
func YEndEQ(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldEQ(FieldYEnd, v))
}

// YEndNEQ applies the NEQ predicate on the "y_end" field.
func YEndNEQ(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldNEQ(FieldYEnd, v))
}

// YEndIn applies the In predicate on the "y_end" field.
func YEndIn(vs ...int) predicate.WallElement {
	return predicate.WallElement(sql.FieldIn(FieldYEnd, vs...))
}

// YEndNotIn applies the NotIn predicate on the "y_end" field.
func YEndNotIn(vs ...int) predicate.WallElement {
	return predicate.WallElement(sql.FieldNotIn(FieldYEnd, vs...))
}

// YEndGT applies the GT predicate on the "y_end" field.
func YEndGT(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldGT(FieldYEnd, v))
}

// YEndGTE applies the GTE predicate on the "y_end" field.
func YEndGTE(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldGTE(FieldYEnd, v))
}

// YEndLT applies the LT predicate on the "y_end" field.
func YEndLT(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldLT(FieldYEnd, v))
}

// YEndLTE applies the LTE predicate on the "y_end" field.
func YEndLTE(v int) predicate.WallElement {
	return predicate.WallElement(sql.FieldLTE(FieldYEnd, v))
}

// HasMap applies the HasEdge predicate on the "map" edge.
func HasMap() predicate.WallElement {
	return predicate.WallElement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MapTable, MapColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMapWith applies the HasEdge predicate on the "map" edge with a given conditions (other predicates).
func HasMapWith(preds ...predicate.ContestAreaMap) predicate.WallElement {
	return predicate.WallElement(func(s *sql.Selector) {
		step := newMapStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WallElement) predicate.WallElement {
	return predicate.WallElement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WallElement) predicate.WallElement {
	return predicate.WallElement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WallElement) predicate.WallElement {
	return predicate.WallElement(sql.NotPredicates(p))
}
