// Code generated by ent, DO NOT EDIT.

package contestareamap

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "Name" field. It's identical to NameEQ.
func Name(v string) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldEQ(FieldName, v))
}

// NameEQ applies the EQ predicate on the "Name" field.
func NameEQ(v string) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "Name" field.
func NameNEQ(v string) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "Name" field.
func NameIn(vs ...string) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "Name" field.
func NameNotIn(vs ...string) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "Name" field.
func NameGT(v string) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "Name" field.
func NameGTE(v string) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "Name" field.
func NameLT(v string) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "Name" field.
func NameLTE(v string) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "Name" field.
func NameContains(v string) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "Name" field.
func NameHasPrefix(v string) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "Name" field.
func NameHasSuffix(v string) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "Name" field.
func NameEqualFold(v string) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "Name" field.
func NameContainsFold(v string) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.FieldContainsFold(FieldName, v))
}

// HasDoors applies the HasEdge predicate on the "doors" edge.
func HasDoors() predicate.ContestAreaMap {
	return predicate.ContestAreaMap(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DoorsTable, DoorsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDoorsWith applies the HasEdge predicate on the "doors" edge with a given conditions (other predicates).
func HasDoorsWith(preds ...predicate.DoorElement) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(func(s *sql.Selector) {
		step := newDoorsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWalls applies the HasEdge predicate on the "walls" edge.
func HasWalls() predicate.ContestAreaMap {
	return predicate.ContestAreaMap(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WallsTable, WallsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWallsWith applies the HasEdge predicate on the "walls" edge with a given conditions (other predicates).
func HasWallsWith(preds ...predicate.WallElement) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(func(s *sql.Selector) {
		step := newWallsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTables applies the HasEdge predicate on the "tables" edge.
func HasTables() predicate.ContestAreaMap {
	return predicate.ContestAreaMap(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TablesTable, TablesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTablesWith applies the HasEdge predicate on the "tables" edge with a given conditions (other predicates).
func HasTablesWith(preds ...predicate.TableElement) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(func(s *sql.Selector) {
		step := newTablesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ContestAreaMap) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ContestAreaMap) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ContestAreaMap) predicate.ContestAreaMap {
	return predicate.ContestAreaMap(sql.NotPredicates(p))
}
