// Code generated by ent, DO NOT EDIT.

package wallpaper

import (
	"entgo.io/ent/dialect/sql"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLTE(FieldID, id))
}

// ImageData applies equality check predicate on the "image_data" field. It's identical to ImageDataEQ.
func ImageData(v []byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldImageData, v))
}

// ContestID applies equality check predicate on the "contest_id" field. It's identical to ContestIDEQ.
func ContestID(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldContestID, v))
}

// ImageDataEQ applies the EQ predicate on the "image_data" field.
func ImageDataEQ(v []byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldImageData, v))
}

// ImageDataNEQ applies the NEQ predicate on the "image_data" field.
func ImageDataNEQ(v []byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNEQ(FieldImageData, v))
}

// ImageDataIn applies the In predicate on the "image_data" field.
func ImageDataIn(vs ...[]byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldIn(FieldImageData, vs...))
}

// ImageDataNotIn applies the NotIn predicate on the "image_data" field.
func ImageDataNotIn(vs ...[]byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNotIn(FieldImageData, vs...))
}

// ImageDataGT applies the GT predicate on the "image_data" field.
func ImageDataGT(v []byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGT(FieldImageData, v))
}

// ImageDataGTE applies the GTE predicate on the "image_data" field.
func ImageDataGTE(v []byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGTE(FieldImageData, v))
}

// ImageDataLT applies the LT predicate on the "image_data" field.
func ImageDataLT(v []byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLT(FieldImageData, v))
}

// ImageDataLTE applies the LTE predicate on the "image_data" field.
func ImageDataLTE(v []byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLTE(FieldImageData, v))
}

// ImageDataIsNil applies the IsNil predicate on the "image_data" field.
func ImageDataIsNil() predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldIsNull(FieldImageData))
}

// ImageDataNotNil applies the NotNil predicate on the "image_data" field.
func ImageDataNotNil() predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNotNull(FieldImageData))
}

// ContestIDEQ applies the EQ predicate on the "contest_id" field.
func ContestIDEQ(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldContestID, v))
}

// ContestIDNEQ applies the NEQ predicate on the "contest_id" field.
func ContestIDNEQ(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNEQ(FieldContestID, v))
}

// ContestIDIn applies the In predicate on the "contest_id" field.
func ContestIDIn(vs ...string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldIn(FieldContestID, vs...))
}

// ContestIDNotIn applies the NotIn predicate on the "contest_id" field.
func ContestIDNotIn(vs ...string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNotIn(FieldContestID, vs...))
}

// ContestIDGT applies the GT predicate on the "contest_id" field.
func ContestIDGT(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGT(FieldContestID, v))
}

// ContestIDGTE applies the GTE predicate on the "contest_id" field.
func ContestIDGTE(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGTE(FieldContestID, v))
}

// ContestIDLT applies the LT predicate on the "contest_id" field.
func ContestIDLT(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLT(FieldContestID, v))
}

// ContestIDLTE applies the LTE predicate on the "contest_id" field.
func ContestIDLTE(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLTE(FieldContestID, v))
}

// ContestIDContains applies the Contains predicate on the "contest_id" field.
func ContestIDContains(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldContains(FieldContestID, v))
}

// ContestIDHasPrefix applies the HasPrefix predicate on the "contest_id" field.
func ContestIDHasPrefix(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldHasPrefix(FieldContestID, v))
}

// ContestIDHasSuffix applies the HasSuffix predicate on the "contest_id" field.
func ContestIDHasSuffix(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldHasSuffix(FieldContestID, v))
}

// ContestIDEqualFold applies the EqualFold predicate on the "contest_id" field.
func ContestIDEqualFold(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEqualFold(FieldContestID, v))
}

// ContestIDContainsFold applies the ContainsFold predicate on the "contest_id" field.
func ContestIDContainsFold(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldContainsFold(FieldContestID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Wallpaper) predicate.Wallpaper {
	return predicate.Wallpaper(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Wallpaper) predicate.Wallpaper {
	return predicate.Wallpaper(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Wallpaper) predicate.Wallpaper {
	return predicate.Wallpaper(sql.NotPredicates(p))
}
