// Code generated by ent, DO NOT EDIT.

package wallpaper

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/LuukBlankenstijn/loom/backend/internal/infra/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLTE(FieldID, id))
}

// ImageData applies equality check predicate on the "image_data" field. It's identical to ImageDataEQ.
func ImageData(v []byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldImageData, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldMimeType, v))
}

// Color applies equality check predicate on the "color" field. It's identical to ColorEQ.
func Color(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldColor, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldUpdatedAt, v))
}

// ContestID applies equality check predicate on the "contest_id" field. It's identical to ContestIDEQ.
func ContestID(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldContestID, v))
}

// ImageDataEQ applies the EQ predicate on the "image_data" field.
func ImageDataEQ(v []byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldImageData, v))
}

// ImageDataNEQ applies the NEQ predicate on the "image_data" field.
func ImageDataNEQ(v []byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNEQ(FieldImageData, v))
}

// ImageDataIn applies the In predicate on the "image_data" field.
func ImageDataIn(vs ...[]byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldIn(FieldImageData, vs...))
}

// ImageDataNotIn applies the NotIn predicate on the "image_data" field.
func ImageDataNotIn(vs ...[]byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNotIn(FieldImageData, vs...))
}

// ImageDataGT applies the GT predicate on the "image_data" field.
func ImageDataGT(v []byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGT(FieldImageData, v))
}

// ImageDataGTE applies the GTE predicate on the "image_data" field.
func ImageDataGTE(v []byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGTE(FieldImageData, v))
}

// ImageDataLT applies the LT predicate on the "image_data" field.
func ImageDataLT(v []byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLT(FieldImageData, v))
}

// ImageDataLTE applies the LTE predicate on the "image_data" field.
func ImageDataLTE(v []byte) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLTE(FieldImageData, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldContainsFold(FieldMimeType, v))
}

// ColorEQ applies the EQ predicate on the "color" field.
func ColorEQ(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldColor, v))
}

// ColorNEQ applies the NEQ predicate on the "color" field.
func ColorNEQ(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNEQ(FieldColor, v))
}

// ColorIn applies the In predicate on the "color" field.
func ColorIn(vs ...string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldIn(FieldColor, vs...))
}

// ColorNotIn applies the NotIn predicate on the "color" field.
func ColorNotIn(vs ...string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNotIn(FieldColor, vs...))
}

// ColorGT applies the GT predicate on the "color" field.
func ColorGT(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGT(FieldColor, v))
}

// ColorGTE applies the GTE predicate on the "color" field.
func ColorGTE(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGTE(FieldColor, v))
}

// ColorLT applies the LT predicate on the "color" field.
func ColorLT(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLT(FieldColor, v))
}

// ColorLTE applies the LTE predicate on the "color" field.
func ColorLTE(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLTE(FieldColor, v))
}

// ColorContains applies the Contains predicate on the "color" field.
func ColorContains(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldContains(FieldColor, v))
}

// ColorHasPrefix applies the HasPrefix predicate on the "color" field.
func ColorHasPrefix(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldHasPrefix(FieldColor, v))
}

// ColorHasSuffix applies the HasSuffix predicate on the "color" field.
func ColorHasSuffix(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldHasSuffix(FieldColor, v))
}

// ColorEqualFold applies the EqualFold predicate on the "color" field.
func ColorEqualFold(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEqualFold(FieldColor, v))
}

// ColorContainsFold applies the ContainsFold predicate on the "color" field.
func ColorContainsFold(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldContainsFold(FieldColor, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLTE(FieldUpdatedAt, v))
}

// ContestIDEQ applies the EQ predicate on the "contest_id" field.
func ContestIDEQ(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEQ(FieldContestID, v))
}

// ContestIDNEQ applies the NEQ predicate on the "contest_id" field.
func ContestIDNEQ(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNEQ(FieldContestID, v))
}

// ContestIDIn applies the In predicate on the "contest_id" field.
func ContestIDIn(vs ...string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldIn(FieldContestID, vs...))
}

// ContestIDNotIn applies the NotIn predicate on the "contest_id" field.
func ContestIDNotIn(vs ...string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldNotIn(FieldContestID, vs...))
}

// ContestIDGT applies the GT predicate on the "contest_id" field.
func ContestIDGT(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGT(FieldContestID, v))
}

// ContestIDGTE applies the GTE predicate on the "contest_id" field.
func ContestIDGTE(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldGTE(FieldContestID, v))
}

// ContestIDLT applies the LT predicate on the "contest_id" field.
func ContestIDLT(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLT(FieldContestID, v))
}

// ContestIDLTE applies the LTE predicate on the "contest_id" field.
func ContestIDLTE(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldLTE(FieldContestID, v))
}

// ContestIDContains applies the Contains predicate on the "contest_id" field.
func ContestIDContains(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldContains(FieldContestID, v))
}

// ContestIDHasPrefix applies the HasPrefix predicate on the "contest_id" field.
func ContestIDHasPrefix(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldHasPrefix(FieldContestID, v))
}

// ContestIDHasSuffix applies the HasSuffix predicate on the "contest_id" field.
func ContestIDHasSuffix(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldHasSuffix(FieldContestID, v))
}

// ContestIDEqualFold applies the EqualFold predicate on the "contest_id" field.
func ContestIDEqualFold(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldEqualFold(FieldContestID, v))
}

// ContestIDContainsFold applies the ContainsFold predicate on the "contest_id" field.
func ContestIDContainsFold(v string) predicate.Wallpaper {
	return predicate.Wallpaper(sql.FieldContainsFold(FieldContestID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Wallpaper) predicate.Wallpaper {
	return predicate.Wallpaper(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Wallpaper) predicate.Wallpaper {
	return predicate.Wallpaper(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Wallpaper) predicate.Wallpaper {
	return predicate.Wallpaper(sql.NotPredicates(p))
}
