[package]
name = "loom-map-editor"
version = "0.1.0"
edition = "2024"
resolver = "2"

[dependencies]
iced = { version = "0.14", features = ['web-colors'] }
loom-map = { path = "../shared/map" }
loom-client = { path = "../shared/client", features = ["map"] }
tonic-web-wasm-client = "0.8"
async-trait = "0.1"
uuid = { version = "1.20.0", features = ["v7", "js"] }
anyhow = "1.0.100"
web-sys = { version = "0.3", features = ["Window", "Location", "UrlSearchParams"] }
console_error_panic_hook = "0.1.7"
