// Code generated by ent, DO NOT EDIT.

package contestmap

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the contestmap type in the database.
	Label = "contest_map"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldContestID holds the string denoting the contest_id field in the database.
	FieldContestID = "contest_id"
	// FieldMapID holds the string denoting the map_id field in the database.
	FieldMapID = "map_id"
	// Table holds the table name of the contestmap in the database.
	Table = "contest_maps"
)

// Columns holds all SQL columns for contestmap fields.
var Columns = []string{
	FieldID,
	FieldContestID,
	FieldMapID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ContestMap queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByContestID orders the results by the contest_id field.
func ByContestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContestID, opts...).ToFunc()
}

// ByMapID orders the results by the map_id field.
func ByMapID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMapID, opts...).ToFunc()
}
