syntax = "proto3";

package admin.v1;

import "admin/v1/map.proto";
import "buf/validate/validate.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

message Contest {
  string id = 1;
  string name = 2;
  google.protobuf.Timestamp start_time = 3 [(buf.validate.field).required = true];
  google.protobuf.Timestamp end_time = 4 [
    (buf.validate.field).required = true,
    (buf.validate.field).timestamp.gt_now = true
  ];
  optional int32 map_id = 5;
}

message Team {
  string id = 1;
  optional string ip = 2 [(buf.validate.field).string.ip = true];
  string name = 3;
}

message Station {
  int32 id = 1;
  string ip = 2 [(buf.validate.field).string.ip = true];
  google.protobuf.Timestamp connected_at = 3 [(buf.validate.field).required = true];
  optional google.protobuf.Timestamp diconnected_at = 4;
}

message TeamsResponse {
  repeated Team teams = 1;
}

message StationsResponse {
  repeated Station stations = 1;
}

message SetIpRequest {
  string team_id = 1;
  optional string ip = 2;
}

message UploadWallpaperRequest {
  string contest_id = 1;
  optional bytes image_data = 2;
}

message GetWallpaperRequest {
  optional string contest_id = 1;
}

message WallpaperResponse {
  optional bytes image_data = 1;
}

service AdminService {
  // Gets the current or next active contest
  rpc GetNextContest(google.protobuf.Empty) returns (Contest) {}
  // Gets all teams in the current or next active contest
  rpc GetActiveTeams(google.protobuf.Empty) returns (TeamsResponse) {}
  // Gets all registered stations
  rpc GetStations(google.protobuf.Empty) returns (StationsResponse) {}

  // Sets the ip for some team. Only allows ips that are not used by a different team yet
  rpc SetIp(SetIpRequest) returns (google.protobuf.Empty) {}
  // Sets the wallpaper for some contest
  rpc SetWallpaper(UploadWallpaperRequest) returns (google.protobuf.Empty) {}
  // Gets the wallpaper for some contest or the active contest if not set
  rpc GetWallpaper(GetWallpaperRequest) returns (WallpaperResponse) {}

  // Gets all maps in the system
  rpc GetAllMaps(google.protobuf.Empty) returns (GetAllMapsResponse) {}
  // Sets the map for some contest, does not error of either does not exist
  rpc SetMap(SetMapRequest) returns (google.protobuf.Empty) {}
  // Creates a new map
  rpc CreateMap(CreateMapRequest) returns (MapResponse) {}
  // Gets a map
  rpc GetMap(GetMapRequest) returns (MapResponse) {}
  // Updates a map
  rpc UpdateMap(UpdateMapRequest) returns (google.protobuf.Empty) {}
}
