// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Contest is the predicate function for contest builders.
type Contest func(*sql.Selector)

// Station is the predicate function for station builders.
type Station func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)

// Wallpaper is the predicate function for wallpaper builders.
type Wallpaper func(*sql.Selector)
