syntax = "proto3";

package map.v1;

import "buf/validate/validate.proto";
import "google/protobuf/empty.proto";
import "v1/map/types.proto";

message GetMapRequest {
  int32 id = 1;
}

message CreateMapRequest {
  string name = 1;
}

message MapResponse {
  MapMetadata map = 1;
  repeated Element elements = 2;
}

message GetAllMapMetadataResponse {
  repeated MapMetadata maps = 1;
}

message UpdateMapRequest {
  int32 id = 1;
  repeated string deleted = 3 [(buf.validate.field).repeated.items.string.uuid = true];
  repeated Element updated = 4;
}

message AssignStationRequest {
  string station_ip = 1;
  optional string seat_id = 2;
}

service MapService {
  // Gets all maps in the system
  rpc GetAllMapMetadata(google.protobuf.Empty) returns (GetAllMapMetadataResponse) {}
  // Creates a new map
  rpc CreateMap(CreateMapRequest) returns (MapResponse) {}
  // Gets a map
  rpc GetMap(GetMapRequest) returns (MapResponse) {}
  // Updates a map
  rpc UpdateMap(UpdateMapRequest) returns (google.protobuf.Empty) {}
  // Assigns a station to a seat
  rpc AssignStationToSeat(AssignStationRequest) returns (google.protobuf.Empty) {}
}
