syntax = "proto3";

package admin.v1;

import "buf/validate/validate.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "v1/command/command.proto";
import "v1/map/map.proto";

message Contest {
  string id = 1;
  string name = 2;
  google.protobuf.Timestamp start_time = 3 [(buf.validate.field).required = true];
  google.protobuf.Timestamp end_time = 4 [
    (buf.validate.field).required = true,
    (buf.validate.field).timestamp.gt_now = true
  ];
  optional int32 map_id = 5;
}

message Team {
  string id = 1;
  optional string ip = 2 [(buf.validate.field).string.ip = true];
  string name = 3;
}

message Station {
  int32 id = 1;
  string ip = 2 [(buf.validate.field).string.ip = true];
}

message TeamsResponse {
  repeated Team teams = 1;
}

message StationsResponse {
  repeated Station stations = 1;
}

message SetIpRequest {
  string team_id = 1;
  optional string ip = 2;
}

message UploadWallpaperRequest {
  string contest_id = 1;
  optional bytes image_data = 2;
}

message SetWallpaperTextColorRequest {
  string contest_id = 1;
  string color = 2 [(buf.validate.field).string.pattern = "^#?([A-Fa-f0-9]{3}|[A-Fa-f0-9]{6})$"];
}

message GetWallpaperRequest {
  optional string contest_id = 1;
}

message WallpaperResponse {
  optional bytes image_data = 1;
  optional string color = 2 [(buf.validate.field).string.pattern = "^#?([A-Fa-f0-9]{3}|[A-Fa-f0-9]{6})$"];
}

message SetMapRequest {
  string contest_id = 1;
  int32 map_id = 2;
}

message GetMapRequest {
  int32 id = 1;
}

message CreateMapRequest {
  string name = 1;
}

message MapResponse {
  map.v1.Map map = 1;
  repeated map.v1.Element elements = 2;
}

message GetAllMapsResponse {
  repeated map.v1.Map maps = 1;
}

message UpdateMapRequest {
  int32 id = 1;
  repeated string deleted = 3 [(buf.validate.field).repeated.items.string.uuid = true];
  repeated map.v1.Element updated = 4;
}

message StationStatus {
  string ip = 1;
  bool logged_in = 2;
}

message StationsState {
  repeated StationStatus status = 1;
}

message DeleteStationRequest {
  int32 id = 1;
}

message AssignTeamRequest {
  repeated int32 ids = 1;
}

message SubscribtionMessage {
  oneof message {
    command.v1.CustomCommandOutput command_output = 1;
    StationsState status_update = 2;
  }
}

message ClientCommand {
  repeated string ips = 1;
  oneof command {
    command.v1.LoginWithCredentialsCommand login_with_credentials = 2;
    command.v1.LoginCommand login = 3;
    command.v1.LogoutCommand logout = 4;
    command.v1.CustomCommand custom = 5;
  }
}

service AdminService {
  // Gets the current or next active contest
  rpc GetNextContest(google.protobuf.Empty) returns (Contest) {}
  // Gets all teams in the current or next active contest
  rpc GetActiveTeams(google.protobuf.Empty) returns (TeamsResponse) {}
  // Gets all registered stations
  rpc GetStations(google.protobuf.Empty) returns (StationsResponse) {}
  // Delete a station
  rpc DeleteStation(DeleteStationRequest) returns (google.protobuf.Empty) {}
  // Tries to assign a team to each of the stations
  rpc AssignTeam(AssignTeamRequest) returns (google.protobuf.Empty) {}

  // Sets the ip for some team. Only allows ips that are not used by a different team yet
  rpc SetIp(SetIpRequest) returns (google.protobuf.Empty) {}
  // Sets the wallpaper for some contest
  rpc SetWallpaper(UploadWallpaperRequest) returns (google.protobuf.Empty) {}
  // Sets the color of the text displayed on a wallpaper
  rpc SetWallpaperTextColor(SetWallpaperTextColorRequest) returns (google.protobuf.Empty) {}
  // Gets the wallpaper for some contest or the active contest if not set
  rpc GetWallpaper(GetWallpaperRequest) returns (WallpaperResponse) {}

  // Gets all maps in the system
  rpc GetAllMaps(google.protobuf.Empty) returns (GetAllMapsResponse) {}
  // Sets the map for some contest, does not error of either does not exist
  rpc SetMap(SetMapRequest) returns (google.protobuf.Empty) {}
  // Creates a new map
  rpc CreateMap(CreateMapRequest) returns (MapResponse) {}
  // Gets a map
  rpc GetMap(GetMapRequest) returns (MapResponse) {}
  // Updates a map
  rpc UpdateMap(UpdateMapRequest) returns (google.protobuf.Empty) {}

  // Subscribes to the client broadcast
  rpc Subscribe(google.protobuf.Empty) returns (stream SubscribtionMessage) {}
  // Sends a command to the backend that is either send to one or more
  // stations or handled by the backend
  rpc SendCommand(ClientCommand) returns (google.protobuf.Empty) {}
}
