syntax = "proto3";

package station.v1;

import "buf/validate/validate.proto";
import "google/protobuf/empty.proto";
import "v1/command/command.proto";

message CustomCommandOutput {
  string id = 1 [(buf.validate.field).string.uuid = true];
  string output = 2;
  string admin_id = 3;
}

message LoginWithCredentialsMessage {
  string username = 1;
  string password = 2;
}

message CustomCommand {
  string id = 1 [(buf.validate.field).string.uuid = true];
  string command = 2;
  string admin_id = 3;
}

message StationCommand {
  oneof message {
    google.protobuf.Empty sync_wallpaper = 1;
    google.protobuf.Empty sync_contest_url = 2;
    command.v1.LoginCommand login = 3;
    command.v1.LogoutCommand logout = 4;
    command.v1.LoginWithCredentialsCommand login_with_credentials = 5;
    CustomCommand custom_command = 6;
    google.protobuf.Empty start_registration_tool = 7;
    google.protobuf.Empty stop_registration_tool = 8;
  }
}

message StationEvent {
  oneof message {
    google.protobuf.Empty logged_out = 1;
    google.protobuf.Empty logged_in = 2;
    CustomCommandOutput command_output = 3;
  }
}

service StationService {
  rpc Subscribe(stream StationEvent) returns (stream StationCommand) {}
}
